var htmlConfig = {
    bookConfig:
      "v010001102d7aFeg0DVh5EVk5BWjwDWi9BXnwERt9ASv8CTh0OSjuHYk3Nco8Aft8Mdo9EWv3DUg9GYnvBWk6Ifs0FWpwPWs6CQg5PUt7Hbk6Mas1PTv1Cdv1IRp4GZt9Edg6EYt2NSlxKQiyHYl1Ecs7HSk1DWnzJfquFdozAWj2NZm7CfnzNXuzMeq2Kes5GegvPdlyPdv9HQp8OWm4Bbn9Bdu0MYv9Hbt5BSn8JWr3PcrzMbl5Nck3Fer4Gci5AbhvNZk6CdruAel4HZhuBYvwAcs6OdnwASh9Abp1Ofg2EZizCdn5Mds3AShxMXl8Cau4NdoxEfkzMao2GSo9ETnwDTt4CVjyKXovJeqzFUv9Bbg3BcsvPalzASl0GYh6GZnyEZj2IWsyFds2Iar7LQn0EYrvJSrzGbswPcnxEcv5PdgzGQh1ASh9MZsxCSn1Pfr3LZg7AdkvBer0LbpvGYjyGUs0DUo9ITtzKaizKQk5PYnwBZi6Par8NQuzBZjwDXv4OZh2MTq1MRp1ISn0JWt5Gdq0Dan7CQvuNZp8Cfr9JZq7Fam5HXouOWs7PflyMcg6Neg6Efh3FVu6Jej6KQnzHYpwFVs5NfvwOUsxHXnuHbv4Jdh1EXouPRq2DShzFbl8PYjuOanwHWs3Cdn5Afm3FZj3NYl8FQvzMWu9CQs8Maq8LYuzPYi9Dcu0MSp6NagwKVgvJUm1JRpwKdoxEeo6AVs2IWkxDfk9LQkyFal7LdtvITuyOcq7IVm5Cbn4HdquLYkvJQp2FbixAfk4LZjzNWr6OSiyFZhwHZi0NYv5Gdn2PdhzLSjzIXl1HXvuNblxJepuIfl9NapuBaq4AYj1JWv2LXr6EZk0JUn0AZh1AZv6BevvBXg5Cal9NSqyFYg0Mek1PRj9GduuNRj2Cbr9ISj5HTg7Gck1Pdh8IbryMeo7Pfr5BVi4EevwMVh8BYowGbuxHao9Fcm9Lct4EYn2IRiuIbqzGSj2FaqzDTu3FVv7NSp6EZj3Gck2IZk8LTvuGdu5IUsyHVr2KapzHWm8DZkxGdp2Nej1KSgvHZnuEUj8JZr6CbmuJVg7DanwHWtvMZs7AVmuOas7JQi6JUivJbt0BYiyDXk2JQg1Deo7GXv3BQpvBRp5PSmyJYjuOUozDem0DSuvFbvzGQgxHZt8Obv7NQo0NWuvLTp2CUr4OUs7FZo3HTg0BcgzCXl9NVl1Eak1Oal8DYq0Aal0NZh4Mck8EbtyKSruNYqyAek3AQn2Edo9FSg2OVhyNakvMeowCYv4EZr7CSg8MbruNSl0Kdn6IQtvNSm7Ibs6DQgwHXhuNas6FXsxMbuyBSqwIdv5DQuzLTm6Mek3AQu6PXi2NUt2NVm2BRsxOZvyEcjyAatzIVi4Hej2MTnxEbiuOUuxJZh8ATt1Adm0LQmwKZrwLcmyMWu9JVp7GVv0BYvxDfo4CamvNRgyGWkxLTm6Ebu5EQk5Bdo6HfqwHXu5DYl8DdkyKch1MQkzCZk4AYvwJYm3OUj5ASoyDSp0LdqyJRg7FRoxDSv4Ddn9PcmuHZnuHWj7Mdm4JWn5Iem1LTuyOYlvDfnxCWluNevvBSt5EanyITlzMRlzPVo1BWi6JRq8EZmxOUu7DZrvPfgvAdhvJQs6DVpyLZg8EYgyAYh1LZo4NSg6EVvzOQj5Let4BfuuKXqwOanwOUl1BTv4Fcl7KUp6Cdj3Ocu8MWi2FRj2PbsxLftzNQnvNRm5NQi4GcsxPSnvMeq4BXlwJTvyJZk3Ect9DXtuMfk5FTvvNbl1EUs1BYgyCVs3OSu1Nck8Nak1Hdm0HStyCYq0CRm0Jdo0EbvwIWp7KUi6MTlzCSl4ISsyBYo8Jcs9Odo6KRkvFfnxDfs5JSgxBZuuPdtwAep0OVuxOYg1JYs9Cdq1Ddm1ORh0IRt7Fbj2Een5GQr5EUs3LTr7KTv6ORguFeu0AWt0CRouFclxGTn9ISr4NZuuPeszMVn8MWv6CRs8GflwAVgzNfm0BXtzBbq0CWi6KQkxNWh8NUpyFarvISvzFXj9JWl5MVl4ARizHXu7AQlzCfqvBfuyHZl9IcnyNYq0MZm8Dbk8Lcr7Ict2GTrxLUizJQrzFboyNWpwFRq8NTm5Neo1AWn9Kdk5GXkyPWu5Hfs9Hcq1ASvxBWk9ARs0BXi1DWkzHfo8ESh1PRr8HbpxEYk1Pfh3KctzMUhxBQl7JRp9Eei6DUl7DZl1Jau8Bds6DYi2AbmwGTl8Kfk5LTsyEVuzPTsvHVszAbo5CZqyNYnyASl8NZu7NdiuEWq7Jeh8GVn6MahxAbl3DSo1Gct0BdtwMVjvJSi4HSh9LRjvFSi1GYg1AQv9Hco0Pal0MSrxCfs8MWuyAYhuNeo9FfkyGXiuAel3MeryFfk6EZg5FQk2FQn7Ofj2PZkvNcpyPUj1LUu5GTrzNVtzETguObv6HRpzIfqyJdo8Cds8EclzNRryDagzCeq7IVj4KQt7PWs0JVsyIZs8NalzJRj7EYk7HUv5EXk7Oaj1AduuEVlyFXp3GcrwKdiyMSl9Pcs5BVpyLQuxGau0Mfo4MeszBXkwKbp8BZpyEbg3Dcv6Gdo5HRs2JZk0Jfh8KXhxKZn3Aai2JRj8EesxPUg9EVpwKYn6NTizLar4CUs2NYixPVr8ISs1NfnzNdj8PRqyIfn4CXo0Nfh3IQiwFTq8JRpwFcpyMUg0Ecp2FYg5EVh1LVnyIXp7Icp9DTs0OXt7HTnyFWlyPauyCZqvIak3KUj2CYpyDXl3AakvDZv9Fbn4Fbi0Nfo0LUo1FQr8GTiyPVv5IfvuMUnzOYg0MRrxHQquJao2OYjzOat7JTq5MQg8NTiwBbr9ISh3Eep3LfquJbg8JYu7OYg2EevzOTuxIRuxPSi8Gcv5KRg8KWn2Leo3HRt9KatxJak0PQg4CXjuEWu5EUlvIet0Jdu5Ncv1FYk1Ddm1Dbk1EZq7Ocj5CQl7LTp0OTp4JTjzGQvuBbpzNasuMalvEcr0ARv2Ifs0NegzFRtzDYk8EcqzLYg6PSlwEcr9LUn6BTozARgzAUqxKWtvEXtvGXmzDVkwJWk1AXivJek5DQu6BdlxDSrzHft4BXg2MVr4HRkyPdu8Dep4NZh5ASq1FUu3Oeq4CSg9LYo6Lbp9OZk9JZm0KUiuGUq9Ffi3HXnuNUi3BXr9FTgxITh5BUq7Gat3MTu7LQj9MVu4Ncl1LSmyAah2GRtuMau2ESo7Gah2JSq3OdnzJZq1Fak8LZg5IRn6Lam0OZn1NWv6AXj9EQh4GWtvFetuGan2LXv5Jat0MWq4BZoyKfmvCYovJXh6Ifg4DWk0BRp5Cai7KciyLWtxKVj8GduyBYt8LUo2ATowMZgyBUkuNaswCag4GTk3LSg6Ndu3DVjuLfo6FWt3JamyCcl8FUo5AVn2NUk5ITt0NajwDYn7Fen1AZn2LZm2OVouMXq6Gcr1HTr0Hco9GVm4ATh0FajzLTj1JRk7Odk0Ebg4CdryBSivAcvyIeo4DSpwBZo5HWtvHfj5BdouIbtwCZp4EYo6OXk8CXruBcjxDam2BeizGfg4ETp1ETj2FfiuOVr3Cct2Bei4BXpwMVp4Bbk4Ffo0Bch7IXqwGYq5MatwDeu3CQvyLal1GdpzGbtuGRv9FfmyNXs9Beu1AbpwEUuxBQgxGbp7MQhuLZv4PWn1Hes5IXt8Ocp6KboxCfk3Kfg1OVozKakwCVuwDavuObuvHVr3HSsyOck8Efg2IRh4BXrxOcu4Ceq0JajxBVu6GeuzJbkxHag4KUk8PWkwAYj1CSkvCdp6AUo4Fer3NVt0ISnyDas8CalvJRv9Ecp4ETguJdo9CWjwAbo9IZj0AUvxCUvvJSowPeizNas1Ibm0JSg7HSk8DVo2Peu6GTh7MatxAUs3FYouHVm5EWm2JYn5CZpuNXhxLdlwCdk5Afi2Pbt7MYt0FWn7JWp6ASr5Pbg2DQnvOXo5KYv4IVp3DVhxAYq7AavvPSjxHUq6CTo7GXi3ISm0HYj3GVv0MWv5Ndk2EUr2ARi0HeizOWuyCek1Kbs4DRu1Lau1HbgxDckzGZnvNeq5BZr2HQg6Cbr2Kbi3ISj6AYhyLSuzKZkvPZt4HQv5IZn4CVszFfrzPfkvHSk6Pep5CbqxHWnzFTszMZj1HZj5PfqwOVt8AfnyPTsvLSiyLbuvJTs8HUlwAXq0DVg5KWgwARk4Pdv1GTj8Jfg1PZg2AVhyFXpxFYh8MRkvMes0Dbh0ASq1Icv5NchvPVnxIRm1ATh7Dan0GRtwFbrzBdh8Mdq7CavxBUvwOelyKXhzMQn4AWn4JRlwMcl9Nev4DZovJWl5AahwEbguPTi8ORr6KTmwEbo1JVh4GWlxHVo0Kdn1CRoyHSs0Pcj9Ceg1Kai6JVrwFdv3MRm6CcvyETv5BSk0NUmvLZqxOZgvGTu7EVivJch1GUn6Pcl4Jfn8GauwJXs7EWl0Ldt6AQnxMQp8BZn6CQi8FSixERlyIYuvGVh4BWuvKZp5HZl1GVouAYj1MRnxEeu3IZk8BfuvCQqyKbjxNdk3Laj4Aam9FdpxJXpzCfm6BagzEckwBUi2PTgxCfo1Iam4JWuzCRgwNUj5MSr8Deq3NUm7FTm7Acu7Ebq0GXkvAfhyBQi7NTpxEYsxDfi8Dfl8DfgvLRr3KRt3Bcu4Jbj2Dfs5Men4NStyATh8Ecv6NXo9Hej2DUl0HdhvBUq5GbgyCWn0OfnwAUk2MQo1NQg2CVj9KbrzIUr8KVo9DXo8KblwLel6PSj7IbhwCfl3PdrxEbguETmvKXs6FVj8DVh3OZswNWr4NRuxNdl1ITp6DXm3FVvzDZpvETl9GVk1CWr1HbpzIegvASouARt6Dcl9AVj4FcuwGSh5PUo6KXh8IRr7IQhwNVivIUhzEdowJao5KXl2FXmyHZvwKWu1Fej9KRl9DWoyHel1LWs5MapzGahxBXiwLRt5BYl8HavxGQn2LZs0CbhzPXnvCXtuAdj3IfhyNYt2FepzBdjwKfqwBUt3GXowCTrzGQu1KRv5GVsxNdoxLSjyNZm3DShxORj1FXj3DQtxBdg5FagyKUgzJdjzCVn2PZg1LXu8Bco1GUi9GSp9OfvxGTi5MSk9LVo1PfpwMSvzCap8GQn8CWk6IeouPYo2ARj4NRnuOZr9BSuyKXk5HbryBQp4Mbn9KXluFUo1Ldl0DWp2DQp8Cfk5Mbk6DVswDcn5JRmzGfj0Afo2AbrzEbg8NQu0Dco1IRp2NUqzCTi5JQi5EUo2CbuzMav0GVo4GQo7EVsvIct2LfsyCUl6DWp0Ecu0DVr3Aah1Een5Oal8GTiyGTm5AVp8EWj3OTv3OUmzEct5CVs4HSuxBdpzDbl7LZk9LXv5DQjyJUpwOdr4GdrwNeo9LervEVs4MYlwObquBUmyLaluPfu9Jbu8EYqyPYoyJdjvAUm6BTkwJdkxMZkuNeuwGTl2Hap1JYt7JbhyOSi2KegvJSrwDfq3Ffs1BTg5FVmyNUs9HdmxEag1BWj3GVt2OXvuIWg4Pap9KYg4AflyGYr3NXjzAdh1CTu0LZn2MZg4EYhxPTj7DauuNVr0BUr3LegzJdrvCUu7Gag3HQkzPZnxFchyFfn7Pfs4AcrvHci3KVt3LQt4DUl6Maj8OZh6LThvIZmzMYhzMWk4FUlwLat2GVrvDYt5AYkxHVkvEfm8Fcm7CZrxIXt0MZm6JUo2KTl0OSiyHckyJdpxGbq8FQqyMQn5Aai4KVluAYmyGfmuFUq2NUu9LWmxEZl1Ocm9Jfp7OQk1CYv7Nat0JbpwEcl4PSj6NVl6EVoyOWm8PVh6PYj6GRu0Jar6FQr6HaryIXhwHWkyPQv4DUg0Fbp5EaquNXk4NfoxBTlvCUjwHRu1DZo9LWr3Ker6CXl7BRhxKXv6Gco9Bei0DcpuEQjzMZs3DVhuMfp7LXj7Oer8Idm7IelvCWqzOZp5ObvuKSjyLVh7Gep2AfowNWp3Cev5FTv2MQsuHev2FSv9NTn8GVt1MfnyKfh0CZk7CVrxCZl2KenxOWouJYu9CTh8DahyDYq6Mfh7Deu2CZuuCfoyNaq7CXn7Lbh6EfmyPfo9JRh9CZl1Ibk1JSt4KWs0IahvNUn1Gcg2IRjwAcq4NYlwCXt4PZnvBZk5IYowPRq7Deh1ASt1BaqwOYo4Ccr3Dcg8EXl7LXs3Dbj2Cen5Lcs7KUp4Mei1BSp8PWm1AWn4KTruIYvyHdtzHYuyMWuxHSg3Cap4MWpuDVs3IdjwLRjyITh9PVi1EQj7MUlzBcjwPUkzGQl1MXuuLVt0Kdk3ARvwGRrxFbr7NSr9AXg2CQluKYv4JUtzNYt8DTt2LYk2MSv0Idp9Nbr5Oak9DRh0MTh0Jdo7Gbn7Ffj0AfhwDeu1KYg5NfnvFQr5CYuyFWt6DQo0Edo5KSk8Aal9Abp3JarwIcu2DSv2DanzMbh1PckuGamxNWo5ISp6FbpwISj3PcpyHcvzAWi0ATr0MZrvETh2EauxFcl9LRsuIRuyDem5Lfh8JVhwPYp5Cbn6EYnxGVk9Kel1MYoyJcj5KZr7Bej2HYt5PQo6Bck4BZg0BWm7IVs1HZp6BQm2EYivHYuvNfv8MRmzARvuNRo7Met2DWrwIeo0Gfn8PZm0OXm5HYi2Dam9ARl3HdrzDSjxLYivMWk5BUv1Pak9EYpvOUv1OZkvISp1JXq3PejyGSs2EUo2PUi7HTu0DSmuLeh8Ifl9Nfi1OZpyPak8FWjyMaj4IUl5LRgxOTu4JUswPXi5ARo1ESn2LQi8HWlxCShzGSv8Lfp2HUpxGWqyKZowFbo3NasuOQk5IXq5HcixMQr5JXtwBQq2PYi3FbtwNStzGZnyKUu2FTo8LWl0HQi7LatyFQjzMQr5Cah8Cdr1Aal9Oet0JWo5PdsxMVvzAQt4NZt5HQvwLeg1IXjyCal1LSjzGdhuFRt8LcoxNUi3Bbv1Odt3KUsyPbs3FWg3HZp9PQl3PcouKdhuBRh5GcuwGTq3Dfl6Ier4ERuwBWlyMYmuDZm9CaquNZnwGUq3MXs5MUq2IRvvIUs6Mdh3PSn2NbvwNag0LcqzEXo7KSgyAam8FZq5Dfu2ERm9OcrzEZg7Adm4BalyHYp2DapwPeq8GZt9CSh3HWq0IUj2HZo5Lap2OTu5IZs3MTuwBVpwFckvMQk2Fdh4BVnyCWr5JdqyNSowPTmxJZj3ARi2DQi6KTiyOTnuIbj7BfpyLfm1HWtuPUr0EQn6HYgyMXv8Aal2NUv6BUtyAbnvJfg0GSl2FRpuPTg1FUr5Kel6LTixGdn1Adu2AXu7Kbt0IaryGRs8PahyMeo5HcnyDfu1EQv1IeqvPav1EUpxJTo3OYqzFUtvGRv5PTi8Abq6Maj5Pbr3Kci2BRmzKYpvHQq0GQn2DZm0BRlzMct9BYr5Bbk5Mfi7DRjuCbq6PXo3Fbm4Hcu3HXp5HUj8BXizKQmuFes6BTl7MSr9Pdq7AarxLYoxJUnvJbq5AZh1ORvwDak7NYnzCZg6Mfl8NSjvIRk2GXluFeq3DagxKdk7MYozKXg9EVl3BSj4DWg1OYvyFRu3ORqxLei7Jfl3FYmvNTlxGQg2DRpyOdtzCSs4FSg2MVtyMRq4HThxHWtzLatwLWn2AVu3KelyGen3CTn3KSk0PTl5KRvwEVuvEUr9LYq5NfuwGav9MXsyOTq1CYq1Cet9CRg7Afh4JVo0Ndl0Ebv9BTt0ATvxEXm4Adv5GYu8Dan0Kev9Efr5BUhxNdvuHev9JQl8EUr9JWs3Jbu0Kbt7CUg1MZq1PTjyCUu6BXo0OeiwJWjxEav9DchuEZozITi5AVm4Mag3Baq0GZn3MWs2IeuxFXk4EUluMTmvAcq0PRi4AXn4KQh8Kbs7FQs2Cbp2Adp8Efo7OXgyEUi3MTmyEXp7Paj7HfuuFVn4AWm5Hcl2Gct2IelzHfqzHeo5BQm3Oeo6DUhzIcv9GXkxKfizDekvAeo5BSqzPXgxGYlxMRluPVs7Pem1Gfs4Pft4PXn5CSg9MVk9PZpuCWo6Bfp9GYl5FSp9NRoyKXv4PbjvFbj4MSv7Mbh1HWm9IWk2AWiwERr3NUiwHUhuMal0GfiwBYv7KegyLfk6Edq1FZnzKduvOfkxKUo5GZp4MWr0Mbh8Gdp1GWq4ERuuHbqyPUryGfouPcn0Den8BVm5BUgwIZm1LWh9Ldh7LdoxIaj6PSk9LVh6Mcr7JftyDamzGTh9EQt1Nav4CbiuPQo7KYszJSk6Oeg4LYr3FbrzIWtuCYvyCRhzCah1LXouLUmxMWh9Kan3NSjuAbn8GWq5AXmuIfkxIZrzLZhyHRv9BVm1Mch1DduzNYu6AZm9NRg9ITu8ATi3BbqxFfpuASgzDcj3DWv7PTj7LWrvMVh1GYpzOZk2PfrzDeh7IQqyLZt8PRk0GYswBXnxBSg2CaiyMbovHWhzPeqzJVo4EZr6PXgvCRqzEYnyHSn1Ddl7CVryJas0LQm6HTq8OflzBVu4ETm6KesyDaruEYszFfi3Kcu1HXixJZm5Dak7Ges0DeqvHYj7DSs1Ifh6AZl8ARszKdj0Kfh5OcnyFWg8Efo0ERhvLRoxEbk9GYrvPVjvOTj6LbvzEVl8BUmxHXh5GWl3Cet0FfjvGVn0Ldu2FXl9Lcj4Hcu1EYv2Aal0CWo1BQr1MRvwIaiuBcm3BRi9EYj7BQt5KQo2Fcj2PavuIXouFbgzMWt2ARnxAYhxMQl5Bdk3LXlxOaoxFZoyKel4LbnxKQr7FRn4Hfu2CVm0Jdq6PSv3EcmzNWg1HYh8NUl0DYi7GRvwDbnwETo1LagyOcu9ARpwLVr8FbpxGctvMQj7EYh1Edg5BXo4MRu0Nat7JdgyMbr9EYj4KXs0IWqwDel2EbpyMaq2MTmxFTqvOXk9GYtxDYhzCVn3NWo7FXo1Del3NQg5MXjzLZjuJepvOfv8Ods6GWnwEel3MZqyAUh5FdivIUuwMdj8CVjyEci9Met0LWj9DZjxBeguDYo1AUtvIelyHSp9AQs6Edp5HVoyBchwCZv7Pfk4FWv7CTkxASi2Nfn3NRo8BWh0JUmwPSuzDWlzIeh8Pct6FRk0MTo4JRguLag3HXizEVr3MVj8NXp8Ieo4DYj7Pbv3PRr6MRi3Fbr8OQlxBcuwPbt6CXi1MWi4GQv9HcswAfg6IVg7PUn1Leg5AYu5BfjvLRvxPdkwLXo3Cai2MUr2HfiyDTp7OVg4BUg7JYsyKThwMaouHej8OWk4JQozPUo7Ebo5OZrvPQjyCYuvKRqyJeivDetzEZvyLXr0MSixIdpxGUp3Ebr6Ocm2ERn5CSr1KRhxGQkvHQgyMbn4GcovHcizNZu4BTgyFdtxDVvuLZlwKXl8BQhxPYtyPTk8Cak5Hah5HZi9CbhuPQp3HdgyLei8AYi2EQj3Oet8Feh2IQizPet7MTg2PbryGUs9Bdq9BVrwASn6AXtuKUq1PWs7AWv1EcovKTouAfiwHYsxCRt1IZu3Nft8EcqzEdp1GVl1ITm9HWm9Ddv5FUp6EZm2Das9MZg5DUlxDcnwMVu8MZh5Keo5AfkzMek0GQhzDdg1MSvzKQu2BRruOSk6JVtzOTo7Hcj1KdgxAdk3Jfu6BXi8PRiuHVuyJStwJar9HUh6JXn5LbixPUh8Cch6Oeo6OVowNVn0BQgvPZjuPRm2KVuxIZrzOXg5LbruPcjzPUluORm5IUh0ATjzBRhuMcp5ASmxGct1BdhxAYp7Ebm8GQivBQhuDUpzPVquLWq3ETk6BUt8HUq5AZp5AWguCYp7EQgwKbt3CXo4ETk9CSp5Cfr7JcnxFSowFSk1CWtwFSqvFTq9LRiuDQgvCUguEZi8NUj1Mfi2CVj8GalyDSl0Gem7FZm8DftuGXp1Cbq4LQmwCShzGVv3HSr5NUlvMXkvORgxLQpvNYu0GXq9KVhxDbi3FanzOXkvAfh8KZiuPTi1HQu3Dck4BQgxFep5Fch3PagxJah3AVs0KZq8PWt7GSt2MTu2ESjuJRs8DTlyGarvDSi3ASlyKSu6FckzLRpuBUh6FRt4Jek6Kel4Pfh8KTivKRu8AZk7FfvyPdn2Mfu8KXtzKTj0MYr6Leu7CVr2Aco4FXk3MXjxPRq0JYs2EXkvKYtyFUi0HVl4NRv8CZpwKck8IalyCag5Nfu1KTq9Jdl9DQk5FVgzCYkzNZu5PVl5HUm4Bfm2CYo7GWmvCam2Gfo6OXo0NUv8Iep4Pfh2JTk3BZsuOSt5Icq8Lem6Nau6MQnyCcs8IQouOYq4KfuwGdh8FXg0Ndm8GWu8Fer9Kar5NTp3MQj9LRi1HUnxKRtwCTvvHYv8LUpyLQk5BQizISpuHVkuAWl1ORr9NQn5BUg0CZs8BYpvLft0JYj2Adn3PUpuNYk6Hfq1LUs0Ndv9AfoxKTg4Ecg7PQg4Har4EQl3IVp1PYg0Mbn1AQg7GRhvEdhzOWgyGUn0PSr9KVjuAQnyPct9DWpxBTtzNVh4AThuEQlzCTtzBZq7GXhxNVnzFQixOak0LZr1DQq6Oap9Beu1ORp7PUlxOUixGVm3PdsxIdr3Dek7HTpzCVs7Lai7KUr5JYi5GZs0AUozBUjwBau7Fel9OfuxJaoyETj7NZl7BTsyEVu3EfuxBen3Edn7AZjwJWu5KSuxGRj2LZv8AYn7Jdg9Ocs5PVhvJbg3LQiuJYnwEQl1DWtuGXnyDRs9GWi3Icm0ITpuIfvzOZp1FZm9ITruCep7FTj0Jdg1Lcs9Haj3BenuMahxASl5ASh3NalzCYlwLQluHXiwHRs7CYi8GXh4Cei6KWtwFbt0CRlxAZk3AQhwAVnyEXp5MXr3HZk1Bal8JYi9HajvNRu7BRs3HWsxMchuMfhzLWouDeoxPel0JZo8BWu1Paq2ATk1DXuuNdnvGRr9IeiwDetuCZvuEbv2KdlzBWo6Icn5Cdv9HbuwLRo7HVozOTh9Gfu4Ffi9Ian4MTo4JYk1MYi2GTnuFQp8AZj3FWs2GVs2DRn8JUh8OXp3FTm7GYrwNUn8DTs1Pel3DZj7OXivOZhwHQtuGaryDStzJXkzHQv7Dct7IYu7DXh6PQsuGZmwBaguIWo9Kcp8JYpxKXmyKat1JdmvHci4ETj7ERo3OZo5DRv6JQryIVrzJSm1CQrxKTkuOaq3Gdk2KegxEVi5Peq7OSi3OQv2NQv9BVt6Bfv4Nbu7ESr9OWs4BRh1OUs7PSt1FZk3Kcl9MSoxMfn9LZmzOZs2Hcp1HVl1OXm1AYquDWjzOUq2Edv3GdsxIYjzBRryCSs0JUq7Ncp8CTn8HXt8LavzBWg4JQhuJfj6Ddi9GbiyPQi2BSu1FTr4MWt5Gao9EQq4DVhuOTk0GRi6LWrxBbu6AQh5FRt6Acr9Ibi7GUo9GWu7FSv1Fam9FSq4MSkuIXnuMds8BWr5AXg8GSu4BUg9NapuAaqvFRqyDUt9BRn2NctzCRj4PQlxFQj4EarzLfk9HVhyNRmuNdiyIRl7KQuvJdswCVh6KcmzAVlvDQt3Ndp4PUv9IQqwNdozOZlxLXtyAcrxPWh2AWsyPQlxJbtzBfhwKbnwIdr9OZoyKRlvMRi0Far9FRETmuHQl0EVl5HTlxHSk9DQn5HUw9939ec8117f809649c6670a180502310720",
    aliasConfig: {
      appName: ["", "", ""],
      totalPageCount: [],
      largePageWidth: [],
      largePageHeight: [],
      normalPath: [],
      largePath: [],
      thumbPath: [],
      ToolBarsSettings: [],
      TitleBar: [],
      appLogoIcon: ["appLogoIcon"],
      appLogoLinkURL: ["appLogoLinkURL"],
      bookTitle: [],
      bookDescription: [],
      ButtonsBar: [],
      ShareButton: [],
      ShareButtonVisible: ["socialShareButtonVisible"],
      ThumbnailsButton: [],
      ThumbnailsButtonVisible: ["enableThumbnail"],
      ZoomButton: [],
      ZoomButtonVisible: ["enableZoomIn"],
      FlashDisplaySettings: [],
      MainBgConfig: [],
      bgBeginColor: ["bgBeginColor"],
      bgEndColor: ["bgEndColor"],
      bgMRotation: ["bgMRotation"],
      backGroundImgURL: ["mainbgImgUrl", "innerMainbgImgUrl"],
      pageBackgroundColor: ["pageBackgroundColor"],
      flipshortcutbutton: [],
      BookMargins: [],
      topMargin: [],
      bottomMargin: [],
      leftMargin: [],
      rightMargin: [],
      HTMLControlSettings: [],
      linkconfig: [],
      LinkDownColor: ["linkOverColor"],
      LinkAlpha: ["linkOverColorAlpha"],
      OpenWindow: ["linkOpenedWindow"],
      searchColor: [],
      searchAlpha: [],
      SearchButtonVisible: ["searchButtonVisible"],
      productName: [],
      homePage: [],
      enableAutoPlay: ["autoPlayAutoStart"],
      autoPlayDuration: ["autoPlayDuration"],
      autoPlayLoopCount: ["autoPlayLoopCount"],
      BookMarkButtonVisible: [],
      googleAnalyticsID: ["googleAnalyticsID"],
      OriginPageIndex: [],
      HardPageEnable: ["isHardCover"],
      UIBaseURL: [],
      RightToLeft: ["isRightToLeft"],
      LeftShadowWidth: ["leftPageShadowWidth"],
      LeftShadowAlpha: ["pageShadowAlpha"],
      RightShadowWidth: ["rightPageShadowWidth"],
      RightShadowAlpha: ["pageShadowAlpha"],
      ShortcutButtonHeight: [],
      ShortcutButtonWidth: [],
      AutoPlayButtonVisible: ["enableAutoPlay"],
      DownloadButtonVisible: ["enableDownload"],
      DownloadURL: ["downloadURL"],
      HomeButtonVisible: ["homeButtonVisible"],
      HomeURL: ["btnHomeURL"],
      BackgroundSoundURL: ["bacgroundSoundURL"],
      PrintButtonVisible: ["enablePrint"],
      toolbarColor: ["mainColor", "barColor"],
      loadingBackground: ["mainColor", "barColor"],
      BackgroundSoundButtonVisible: ["enableFlipSound"],
      FlipSound: ["enableFlipSound"],
      MiniStyle: ["userSmallMode"],
      retainBookCenter: ["moveFlipBookToCenter"],
      totalPagesCaption: ["totalPageNumberCaptionStr"],
      pageNumberCaption: ["pageIndexCaptionStrs"],
    },
    aliasLanguage: {
      frmPrintbtn: ["frmPrintCaption"],
      frmPrintall: ["frmPrintPrintAll"],
      frmPrintcurrent: ["frmPrintPrintCurrentPage"],
      frmPrintRange: ["frmPrintPrintRange"],
      frmPrintexample: ["frmPrintExampleCaption"],
      btnLanguage: ["btnSwicthLanguage"],
      btnTableOfContent: ["btnBookMark"],
      btnExitFullscreen: ["btnDisableFullScreen"],
      btnFullscreen: ["btnFullScreen"],
      btnHome: ["homebtnHelp"],
      btnMore: ["btnMoreOptionsLeft"],
      frmToc: ["btnBookMark"],
      frmSearch: ["btnSearch"],
      frmLinkLabel: ["lblLink"],
    },
    meta: {
      htmlTemplate: "Popular",
      theme: "Default",
      title: "Mẫu Thiết kế - Gia công Tem VN Check",
      description: "",
      url: "https://online.fliphtml5.com/epfum/nwth/index.html",
      pageCount: 10,
      pageWidth: 1440,
      pageHeight: 810,
      template: "Popular",
    },
    "project-config": [],
    bmtConfig: [],
    videoList: [],
    staticAd: { haveAd: false },
    language: [
      {
        language: "English",
        btnFirstPage: "First",
        btnNextPage: "Next Page",
        btnLastPage: "Last",
        btnPrePage: "Previous Page",
        btnDownload: "Download",
        btnPrint: "Print",
        btnSearch: "Search",
        btnClearSearch: "Enter key to search",
        frmSearchPrompt: "Clear",
        btnBookMark: "Table of content",
        btnHelp: "Help",
        btnHome: "Home",
        btnFullscreen: "Fullscreen",
        btnSoundOn: "Sound On",
        btnSoundOff: "Sound Off",
        btnShareEmail: "Email",
        btnSocialShare: "Social Share",
        btnZoomIn: "Zoom In",
        btnZoomOut: "Zoom Out",
        btnDragToMove: "Move by mouse drag",
        btnAutoFlip: "Auto Flip",
        btnStopAutoFlip: "Stop Auto Flip",
        btnGoToHome: "Return Home",
        frmHelpCaption: "Help",
        frmHelpTip1: "Double click to zoom in or out",
        frmHelpTip2: "Drag the page corner to view",
        frmPrintCaption: "Print",
        frmPrintBtnCaption: "Print",
        frmPrintPreparePage: "Preparing Page:",
        frmPrintPrintFailed: "Print Failed:",
        pnlSearchInputInvalid: "The search text is too short.",
        loginCaption: "Login",
        loginInvalidPassword: "Not a valid password!",
        loginPasswordLabel: "Password:",
        loginBtnLogin: "Login",
        loginBtnCancel: "Cancel",
        btnThumb: "Thumbnails",
        lblPages: "Pages:",
        lblPagesFound: "Pages:",
        lblPageIndex: "Page",
        btnAbout: "About",
        frnAboutCaption: "About & Contact",
        btnSinglePage: "Single Page",
        btnDoublePage: "Double Page",
        tipChangeLanguage: "Please select a language below...",
        btnMoreOptionsRight: "More Options",
        btnFit: "Fit Window",
        smallModeCaption: "Click to view in fullscreen",
        btnAddAnnotation: "Add Annotations",
        btnAnnotation: "Annotations",
        FlipPageEditor_SaveAndExit: "Save and Exit",
        FlipPageEditor_Exit: "Exit",
        DrawToolWindow_Redo: "Redo",
        DrawToolWindow_Undo: "Undo",
        DrawToolWindow_Clear: "Clear",
        DrawToolWindow_Brush: "Brush",
        DrawToolWindow_Width: "Width",
        DrawToolWindow_Alpha: "Alpha",
        DrawToolWindow_Color: "Color",
        DrawToolWindow_Eraser: "Eraser",
        DrawToolWindow_Rectangular: "Rectangular",
        DrawToolWindow_Ellipse: "Ellipse",
        TStuff_BorderWidth: "Border Width",
        TStuff_BorderAlph: "Border Alpha",
        TStuff_BorderColor: "Border Color",
        DrawToolWindow_TextNote: "Text Note",
        AnnotMark: "Bookmarks",
        lastpagebtnHelp: "Last page",
        firstpagebtnHelp: "First page",
        aboubtnHelp: "About",
        screenbtnHelp: "Open this application in full-screen mode",
        helpbtnHelp: "Show help",
        searchbtnHelp: "Search from pages",
        pagesbtnHelp: "Take a look at the thumbnail of this brochure",
        bookmarkbtnHelp: "Open Bookmarks",
        AnnotmarkbtnHelp: "Open Table of content",
        printbtnHelp: "Print the brochure",
        soundbtnHelp: "Turn on or off the sound",
        sharebtnHelp: "Send Email to",
        socialSharebtnHelp: "Social Share",
        zoominbtnHelp: "Zoom in",
        downloadbtnHelp: "Downdlaod this brochure",
        pagemodlebtnHelp: "Switch Single and double page mode",
        languagebtnHelp: "Switch Lauguage",
        annotationbtnHelp: "Add Annotation",
        addbookmarkbtnHelp: "Add Bookmark",
        removebookmarkbtnHelp: "Remove Bookmark",
        updatebookmarkbtnHelp: "Update Bookmark",
        btnShoppingCart: "Shopping Cart",
        Help_ShoppingCartbtn: "Shopping Cart",
        Help_btnNextPage: "Next page",
        Help_btnPrePage: "Previous page",
        Help_btnAutoFlip: "Auto filp",
        Help_StopAutoFlip: "Stop atuo filp",
        btnaddbookmark: "Add",
        btndeletebookmark: "Delete",
        btnupdatebookmark: "Update",
        frmyourbookmarks: "Your bookmarks",
        frmitems: "items",
        DownloadFullPublication: "Full Publication",
        DownloadCurrentPage: "Current Page",
        DownloadAttachedFiles: "Attached Files",
        btnCopy: "Copy Button",
        infCopyToClipboard: "Your browser does not support clipboard.",
        restorePage: "Would you like to restore your previous session?",
        tmpl_Backgoundsoundon: "Background Sound On",
        tmpl_Backgoundsoundoff: "Background Sound Off",
        tmpl_Flipsoundon: "Flip Sound On",
        tmpl_Flipsoundoff: "Flip Sound Off",
        Help_PageIndex: "The current page number",
        tmpl_PrintPageRanges: "PAGE RANGES",
        tmpl_PrintPreview: "PREVIEW",
        btnSelection: "Select Text",
        loginNameLabel: "Name:",
        btnGotoPage: "Go",
        btnSettings: "Setting",
        soundSettingTitle: "Sound Setting",
        closeFlipSound: "Close Flip Sound",
        closeBackgroundSound: "Close Backgorund Sound",
        frmShareCaption: "Share",
        frmShareLinkLabel: "Link:",
        frmShareBtnCopy: "Copy",
        frmShareItemsGroupCaption: "Social Share",
        frmPanelTitle: "Share it",
        frmShareQRcode: "QRCode",
        TAnnoActionPropertyStuff_GotoPage: "Go to page",
        btnPageBack: "Backward",
        btnPageForward: "Forward",
        SelectTextCopy: "Copy Selected Text",
        selectCopyButton: "Copy",
        TStuffCart_TypeCart: "Shopping Cart",
        TStuffCart_DetailedQuantity: "Quantity",
        TStuffCart_DetailedPrice: "Price",
        ShappingCart_Close: "Close",
        ShappingCart_CheckOut: "Checkout",
        ShappingCart_Item: "Item",
        ShappingCart_Total: "Total",
        ShappingCart_AddCart: "Add to cart",
        ShappingCart_InStock: "In Stock",
        TStuffCart_DetailedCost: "Shipping cost",
        TStuffCart_DetailedTime: "Delivery time",
        TStuffCart_DetailedDay: "day(s)",
        ShappingCart_NotStock: "Not enough in stock",
        btnCrop: "Crop",
        btnDragButton: "Drag",
        btnFlipBook: "Flip Book",
        btnSlideMode: "Slide Mode",
        btnSinglePageMode: "Single Page Mode",
        btnVertical: "Vertical Mode",
        btnHotizontal: "Horizontal Mode",
        btnClose: "Close",
        btnBookStatus: "Book View",
        checkBoxInsert: "Insert Current Page",
        lblLast: "This is the last page.",
        lblFirst: "This is the first page.",
        lblFullscreen: "Click to view in fullscreen",
        lblName: "Name",
        lblPassword: "Password",
        lblLogin: "Login",
        lblCancel: "Cancel",
        lblNoName: "User name can not be empty.",
        lblNoPassword: "Password can not be empty.",
        lblNoCorrectLogin: "Please enter the correct user name and password.",
        btnVideo: "VideoGallery",
        btnSlideShow: "SlideShow",
        btnPositionToMove: "Move by mouse position",
        lblHelp1: "Drag the page corner to view",
        lblHelp2: "Double click to zoom in, out",
        lblCopy: "Copy",
        lblAddToPage: "add to page",
        lblPage: "Page",
        lblDescription: "Title",
        lblEdit: "Edit",
        lblDelete: "Delete",
        lblRemoveAll: "RemoveAll",
        tltCursor: "cursor",
        tltAddHighlight: "add highlight",
        tltAddTexts: "add texts",
        tltAddShapes: "add shapes",
        tltAddNotes: "add notes",
        tltAddImageFile: "add image file",
        tltAddSignature: "add signature",
        tltAddLine: "add line",
        tltAddArrow: "add arrow",
        tltAddRect: "add rect",
        tltAddEllipse: "add ellipse",
        lblDoubleClickToZoomIn: "Double click to zoom in.",
        frmShareLabel: "Share",
        frmShareInfo:
          "You can easily share this publication to social networks.Just cilck the appropriate button below.",
        frminsertLabel: "Insert to Site",
        frminsertInfo:
          "Use the code below to embed this publication to your website.",
        btnQRCode: "Click to scan QR code",
        btnRotateLeft: "Rotate Left",
        btnRotateRight: "Rotate Right",
        lblSelectMode: "Select view mode please.",
        frmDownloadPreview: "Preview",
        frmDownload: "Download",
        frmHowToUse: "How To Use",
        lblHelpPage1: "Move your finger to flip the book page.",
        lblHelpPage2: "Zoom in by using gesture or double click on the page.",
        lblHelpPage3:
          "Click on the logo to reach the official website of the company.",
        lblHelpPage4:
          "Add bookmarks, use search function and auto flip the book.",
        lblHelpPage5: "Switch horizontal and vertical view on mobile devices.",
        TTActionQuiz_PlayAgain: "Do you wanna play it again",
        TTActionQuiz_Ration: "Your ratio is",
        frmTelephone: "Telephone list",
        btnDialing: "Dialing",
        lblSelectMessage: "Please copy the the text content in the text box",
        btnSelectText: "Select Text",
        btnNote: "Annotation",
        btnPhoneNumber: "Telephone",
        btnWeCharShare: "WeChat Share",
        btnMagnifierIn: "Magnifying Glass",
        btnMagnifierOut: "Magnifier Reduction",
        frmShareSmallProgram: "smallProgram",
        btnMagnifier: "Magnifier",
        frmPrintPrintLimitFailed: "Sorry, you can't print the pages.",
        infNotSupportHtml5:
          "HTML5 is not supported by your current web browser, please read the book with latest verson web browser. Here we recommend you to read it with Chrome.",
        btnReport: "Report",
        btnDoubleSinglePage: "Page switch",
        btnDownloadPosterPrompt: "Click to download the poster",
        infLongPressToSavePoster:
          "Press and hold the mobile terminal to save the poster",
        infLongPressToIndentify: "Long press to identify QR code",
        infScanCodeToView: "Scan code to read",
        frmaboutcaption: "Contact",
        frmaboutDESCRIPTION: "Description",
        frmaboutAUTHOR: "Author",
        frmaboutADDRESS: "Address",
        frmaboutEMAIL: "Email",
        frmaboutWEBSITE: "Website",
        frmaboutMOBILE: "Mobile",
        infDeleteNote: "Do you want to delete the note?",
        proFullScreenWarn:
          "Current browser does not support full-screen,Please use Chrome for best results",
        btnBack: "Backs",
        frmVideoListTitle: "Video list",
        frmVideoTitle: "Video",
        lblConfirm: "Confirm",
        frmBookMark: "Book Mark",
        btnExitFullscreen: "Exit fullscreen",
        btnMore: "More",
        frmPrintall: "Print All Pages",
        frmPrintcurrent: "Print Current Page",
        frmPrintRange: "Print Range",
        frmPrintexample: "Example: 2,3,5-10",
        frmPrintbtn: "Print",
        frmaboutcontactinformation: "Contact Information",
        frmSearch: "Search",
        frmToc: "Table of Contents",
        btnTableOfContent: "Show Table of Contents",
        frmLinkLabel: "Link",
        frmQrcodeCaption:
          "Scan the bottom two-dimensional code to view with mobile phone.",
        btnLanguage: "Change Language",
        msgConfigMissing:
          "Configuration file is missing, unable to open the book.",
        lblSave: "Save",
        accessRestrictedTitle: "Access Restricted",
        enterYourName: "Enter your name",
        enterVisitCode: "Please enter your password",
        enterReadingCode: "enter your reading code",
        enterTheReason: "Enter your reason for application",
        enterPhoneNumber: "Enter your email address",
        enterVerificationCode: "Enter your verification code",
        getVerificationCode: "Send",
        sendValidCodeSuccess: "Verification code sent",
        getVerificationCodePrompt: "Get a verification code sent to your email",
        enterPasswordPrompt: "Password required to proceed reading",
        leaveMsgSimilarBooks: "Explore More Books",
        leaveMsgToAuthor: "Contact Author",
        leaveMsgName: "Your Name",
        leaveMsgContact: "Your Contact Information (visible only to the author)",
        leaveMsgEnter: "Please Enter the Message",
        leaveMsgCancel: "Cancel",
        leaveMsgCommitTitle: "Submit",
        leaveMsgPrompt: "We will forward your message to the book uploader.",
        leaveMsgErrorPrompt: "Exception occurred. Please try again later",
        readingCodeErrorPrompt: "Invalid reading code. Please try again",
        passwordErrorPrompt: "Invalid password. Please try again",
        invalidPhoneNumber: "Invalid number. Please try again",
        invalidEmail: "Invalid Email. Please try again",
        verificationCodeErrorPrompt:
          "Invalid verification code. Please try again",
        codeSendingFrequent: "Frequent operation, please try again later",
        commiteTitle: "Verify",
        shamStopTitle:
          "The author's account privileges have resulted in book access suspension.",
        shamStopSubTitle:
          "Contact <a target='_blank' href='{%host}/homepage/{%uLink}/' style='text-decoration: underline' >the author</a> for further information.",
        shamStopLeavePrompt: "Please complete the question.",
        shamStopLeaveMsgSuccessPrompt: "Send successfully",
        codeSending: "Sending",
        viewFullScreen: "Fullscreen",
        cardsSign: "click to view card",
        frmaboutViews: "Views",
        btnMessage: "Message",
        btnInstructions: "instructions",
        btnArticlePages: "Pages",
        btnArticleList: "Articles",
        btnCalendar: "Calendar",
        btnBook: "Book",
        btnEnlarge: "Enlarge",
        btnReduce: "Reduce",
        btnPrevArticle: "Prev Article",
        btnNextArticle: "Next Article",
        copySuccessfully: "Copy Successfully",
        cardsWechat: "Wechat",
        cardsTelephone: "phone",
        close: "close",
        jumpPageByEnterNumber:
          "Enter the page number to jump quickly to the specified page",
        jump: "Jump",
        relatedContent: "related information",
        brandTitleUndefined: "No brand name is set yet",
        more: "More",
        fold: "Put away",
        otherWorks: "other works",
        flipSound: "page turning sound",
        backgroundSound: "Background music",
        report: "report",
        copySuccessTip: "copy successfully",
        saveSuccessTip: "Saved successfully",
        scanCodeAddMy: "After saving, WeChat scan the code and add my friend",
        saveImg: "save Picture",
        searchTheBook: "Search this book content",
        historicalRecord: "history record",
        searchResultCount: "A total of {%count} results",
        noRelevantResults: "No relevant results",
        changeTheKeyWords: "Try another keyword ~",
        leastWordsTip: "Please enter at least 2 words",
        jumpPageInputTip:
          "Enter the page number to jump quickly to the specified page",
        jumpto: "Jump to",
        foldThumbnailTip: "Click here to put away the thumbnail ~",
        btnLoadingText: "In loading, it's fine soon",
        btnTitleText: "Read now",
        relatedInfoText: "Related Information",
        brandContactFrTitle: "Contact the author",
        shareFromPage: "Share starting from page N",
        TStuffShowInformatin_Width: "Background width",
        TStuffShowInformatin_Height: "Background height",
        TPageList_BlankPage: "Blank page",
        morePanelBookLink: "Link",
        morePanelPoster: "Poster",
        morePanelOtherShare: "Other",
        doublePageTitle: "Rotate the phone to enable double-page reading mode",
        doublePageDescription: "How to set landscape ?",
        doublePageGotIt: "Got it",
        doublePageAndroidSettingStep1: "1.The phone allows auto-rotation",
        doublePageAndroidSettingStep2:
          "2.The browser for reading e-books needs to be set to allow horizontal screen",
        doublePageAndroidSettingStep3:
          "3.Reading books with mobile phone turned sideways",
        doublePageIPhoneSettingStep1: "1.Phone portrait orientation lock off",
        doublePageIPhoneSettingStep2:
          "2.Reading books with mobile phone turned sideways",
        noFilesAvailablePrompt: "No Files Available!",
      },
    ],
    ols: [],
    slideshow: [],
    pageEditor: [],
    flipByAudio: null,
    downloadconfig: {
      pdf: null,
      isDownloadProject: false,
      isDownloadAttach: false,
      attachments: [],
      hideDownloadSinglePage: false,
    },
    assistantConfig: null,
    phoneNumber: [],
    bookPlugin: null,
    fliphtml5_pages: [
      {
        n: ["28d822d2e210feddb5b2121a7def6297.webp"],
        t: "./files/thumb/27ff6ad22fb91bc1613997e5f971ae1c.webp",
      },
      {
        n: ["07cbc40bd8df023578ddef8eccdde6b2.webp"],
        t: "./files/thumb/9bc3a948d4060e5ec8a92262ed7a25ae.webp",
      },
      {
        n: ["b2abc2b8b2c16140035b0696a43ce2cd.webp"],
        t: "./files/thumb/2eb0a1d8cc3ea10ca0d030b42f4b50be.webp",
      },
      {
        n: ["31c562cab32251aeb876d84d35c84a53.webp"],
        t: "./files/thumb/57dfa8ddb931a6a248b80f79b01da4e1.webp",
      },
      {
        n: ["dd126c998ce3dcbb699b01edb16e9daa.webp"],
        t: "./files/thumb/1cc04839a7d4eed9c10584811e0ff32b.webp",
      },
      {
        n: ["6bdb0539973a4608dd1f59659f4fa4d2.webp"],
        t: "./files/thumb/9e654dc4138cc1f1cc0e775ffc39b6e5.webp",
      },
      {
        n: ["3e610053635536d66e3d7e3a1e43dec7.webp"],
        t: "./files/thumb/966884f850c45da40243092b92c879b7.webp",
      },
      {
        n: ["482629051f7b3b604207f6a6910bc91c.webp"],
        t: "./files/thumb/c8797e18f42db740356cfd474a8e8bad.webp",
      },
      {
        n: ["5524ee720ebf1f6db707d06d34c8e41b.webp"],
        t: "./files/thumb/a6dd9294c8db35c990d2db8c553adf54.webp",
      },
      {
        n: ["90c6213d59e5c5de2cd03ad441459f85.webp"],
        t: "./files/thumb/ebca32832312f1330d5a6dc537af3edf.webp",
      },
    ],
    downloadConfig: null,
    fileExist: { pageEditor: 0, plugin: 0 },
    loadingConfig: {
      loadingBackground: "#323232",
      loadingCaptionColor: "#DDDDDD",
      loadingCaption: "",
      loadingCaptionFontSize: "20",
      loadingPicture: "",
      loadingPictureHeight: "150",
      showLoadingGif: "Yes",
      loadingVideo: "",
      loadingDisplayTime: "0",
    },
  };
  