var htmlConfig = {
  bookConfig:
    "v010001102d74OemxMQo6Icj0ATk9LXq6KUhwNfq6DTq4AWi4Dah2OXr9JTt4BRuyLcu8OWlvLWg1KWp3NZm1DUvyDZowBei5Acn6EXo2IavuHfg4FXlzHdowFZp1JeqxEWl8LXluHUpxHXqxBZu0Hah8BdjwIdv2HZpwDRh5KQm0NegvMah3LTs7GYsyNSp4Efq6KTo5AanzMQv8Ffs3Pas4FamxITo1PTr6BQi4DZg6IfmvGUh6Mdu6MdluFWm0JZsxAfk8OSluKah1Gdl8FVoyDUn1IapvJft9FZp8Mar4FZvuNZvwGUi3EYhzBbiwOXvvHQl2MTp4DSm3MTh1CRs8Aev2CZvvAXkwIcq7CUs6JRkxKVu7FQp9CXs1GWk1ARkxGSryDfi3FQhuEXnzJTl3Jdp2GThxOWt6NVt7GTkxKUh0HQiyAWmxOSp7MRnuKbv6AUl9ORv9FTs4OYixBdgyCUp0Oav6MZkwJfmxNVk8Ecs7Ieu2FSu0Kak6Kdl6Man0CejwOcqvNUmuFasyKaoyLQruBWtzFbu9KXm6PYqvFfl8Acp8JVp1MUo5DTvzPehxCXv5GehuLbu0NQu6CZo0JWgzIfgxJSj2Cap9KUgzNdpyPfqzPamzDSvzLZkyLZg8Gau4OXvxOXr6NWl3HRi7JSuwPTtvESg6PZq6OZnyAfpvFWsuFVtuKcr2Jfn4OSu3IesxNTh5IbhxPco7MZm9FUvuPWr6Cfk1NSquOXs1Jfn3OVg9JWhvKRmvLQv5KYhzFRi8Lfn6KcpvGXr4JRjyEat0HRhyGSk3NRjxOSh1CVouJRjyJfhyGcjyNcm3PVswGZl3IWvyKel1BSiwETlyGRovKTn6CWsxMTj8LYsvLYk5GSlxMbj6Lag3Kau3AYn8Obs7EXo1BQkvHUj0GdrvMfn6KUs6Kem4MXu8OWj7NWs3HZh0OSu6Bdl4CUmxOXpzNZv6OfozIdu2AZuzBQo7KduzKalyIer3Bcp4MRt7IUmwDdnxCZm8HenzKehxLXj5KQluDQh6GciyLVi6Eek1Ien9AWj6Mdh5DXmzDep6Gcs5BQk6ERnxDYmvNei2Dcj9HZp2IbkwKdp5NcovEct9JeguNVn4GSi0CSiyBQhxNSjxMfjzMYuuMes7PXg3Pdu2OakvFduyEWv9HYl5Faq4OSr7PRquGdj0Dbn0HVi6Fdt0DWq9BXluATmzKVm1MVq6MWh1HYhuPSv2Gfk5MQgxDeg1AbmxFYjzFYv2PYt3EZg0JVp0PTuuCRm9IdlxNduxNWkuDXt2JWv8BXmwAfr3ParwJYq9Fem8KXq3Pfl1Gfp0Acn3AZl0CXk7GbivHcozETr6BTo0MQiuHfu1Dbp1HUjvJUowDWiyPSquFTi8NZlwOYr4Jag7HVu4Bbp5GXm9LejuOYn6MXruMUmuOVs3Pfk8CRr3DWszLbq5OZsyJRl4Lfp4PWjxDdq9EWnzIch1HXpuJZt8HXnzDXo1OVj3Kfu6Jas6EatzFQkxKRnwPbj2DfozASg2LXp0MWg1JYv2HWlvIVl7Ddn1CaozMSgvNVh5CRm6HXq3AalxNbv3KUg1Pbq3NRr5NehwDbv1HRp9EZnvNelyHVjvHViwDQvzFcqxGRo3OasvCRo3LUo8ISn5Hfr3DYhxObryKYj4NUu7JZiuBbi3PcquCeq2ESnvLQi6IWgvARguIRp5PXnxDRsxHaqwCVkvDeg5GTg6KaguBbmvJQhxOes7Hcs9EekzJfn5IUoxNRo9KQr3DbpzEQu8CTpuFZhxJSj0Nar7Jco8OXt0FRlyDWpvBUgxIRp7LRj1MTjwMYkyFRvvCbt3Hci0LRt3KYt7KSv6AVtxMTm1BZiwNZnvLbt5FXg0OQtxDds6BWiwGRi3MRr3IfiyHXk5Ncg4NQnwJRt8DZg6HblwPen2HXowEejzGWs9LTl8HQkzHdv1JWu5CVg2HRp3Dah9CQnwBVm6Bdt7Kan6KQnwGfj4DQt0Lcq3NRt0NVovKbj4Afh1MYnvGRpwNYivOdgxDSt9DZn6BRk3KVj7CZj5GSv6Lam1LcmvMVsuPYl7JWvxAWquGanwFRm6ATq3OaiyNZuyAXh8Mbr8FQnyIUn1IWs0Ddu4Pds4GUk8AUi6CWlyJftxCau8DUv7OduyCUrzIZg2AQo8MTo3ERi3KSuvDUh3PUr7Kag2LXluKdn8NZrvEbqzBdg0Iav6JRp5Dcv0JSn2LXk0PWi5OXhzPYnvAftzDUu5HYs2Haj5NWt0PXt5AZl9Pcj9BUsuGYuxCavuLaq6LXvyKQk7BUl1HUl7LfluCXo3JfkxKbtxPQguLRr1KWvvNfryIZj2MRi1Hcv3FVs3DWr1Hat4OYl2Dbm8FQv6AXi7GfivIaiwPRu5IavyAShuHaj6MQh4Fcv4NUg7MTu3HWhzIZpyIesvEbp0CUm1Oci1GWszNQl3FWs8JWozDcmwAcv0FRi6Gfh4CTvvNXg6OTs5Mcv4Bfr8Fao0HQjxNdm4Aat1KQs6PSo0CYlxGTkuOYi2Oak9PdlzCRn4MRn8Oal5DZjzKdvyGZg9PfruEWtxIRi0OaowAbr9Gek6Jbm2IRo3BUo8BZovGbl4KYj1KelvIXo3IciwDdh8GRnwAZs0CQhwHaq8MblyDYu8FSm7Kdu4HSl6DTgwDXl0AQu6IdrwEcl8AZj2DVl1Pdr2FTn3HYp8HZt7Efl7MQj4JfvxDclyPWpzHStyFepyEehuFUk8GQo8Oah6HTt7Keu2Nbt3LXu3CSnzISg1Efr8Mbr2LcoxAUqxOcs5Obl4Hcm9Maj3Ncl3AdsuKTm0PYk9IRlzJfr5Ges1ATozAao4KWiuKRi1ATt2PfizPVq2KdnxPbv2Ceg3DUhzHYuyPbkzITq7Ceo8ETv0GUj4AWp3Jep0AdiwCUlvCTg9Bdr8LflwETo5Mao4KRuzAep6NTl2Aep0DTpvCblvDUs5KXuwFYqzHcl4LWk3LWmuFav3KZkxGSjvMWo2NSvzMYq0IUi4Iao2KSu5PZl9Hbi3Pcp3Bcq8Jci9JXu7LQq7CQvuNan2GTkvJYgzBXnwJeluLeiuKZjyKSs5CUr8JbkuBYh4MYn3Oes9FYl3JXq7LUo9NVp5LUiwMdl2ETo5LQqzNch8IYm3IVuwPVr7OcpwPRo4PWm4KSt1PZpxIer4DfmuPVv1Ndu1NfszNXv1OWs9Obt3DchyJQlwEev2Ces7DWhyGXn6MYvxAai9DRm9GUh2Lfn1Aeh3KXj7DfsxBfjyHat1BSs6Gai0KVn4ESs4IajzHYivIZi0KbqyAZuxCWm3LesyIVg3BRj6Ias6OWq7OZo1LQh5AXr9Idv4Eeg7Gdr9CRtxBSl2BWtxCRn1MSuuOeg3NaozEft2GZm1MQj4NXtuNXszLYk5GRmwLVi1Fat7IZuxPVlxOfh3NcjvIYr4EZi1MRi6Ofk4ETs7LUu3GXl5NavyEfh5Fel6Iaq0LRv4HarzHYm1Cbi6ETgyNZh5KRp4DVg4IWo4McrwNVqwFblyOVj8Hak0Fft9AfovNWq7GZgyJSivIWjvAQt7IRq0KRr4LWkzLTq7CevvGVjvGdmuBapwOTtwFahxJVj8OWs9OfkyNXq6ITm2NZszHTr5LZr8Jbi7OctuCSk7EWmwPai3HRkyEXq3Kfu1AYgwERr1Bdt1ESgvPSnvJfo4CcjuCRi9FVs3JYqyIWn1DWo8Oeu5KTn0Eeu6HVg4Idi3OUl7GUu7OckwFQg1HfmzLdv2Icr4CVnuJbj4DRh7ARk6Pan4FcrwMRixFTkxCdmvHVj7JcozPfowLbg0Abp0GTr0Nev7DepwOXhuIcs4Abn8CUgxCRh9OZr9Pfp7LWv5HXp2OYo5NTpyJej9NTqwBeh8MSmuJVu2Adv5JZvxMdp1Heg2FahuKZiyAYsuDcm9DatuMZmyHWvwASh8EWp8CZl7MWj5IQk8Gas2HerxKcoxOej9GQrzAUg0Odj7LbpxPWq4OekyJbv3CWu9KdlzNbr6FXsvHcp8DanyBaq5MRmzKduwPcmxHUn9GSnzGRp4GRs1HUrxDck5OWp0Leo6Lci3ESh2EdluBdmwETmvEXuyLcm6BVh3JZj9CYh6KQn2GTrxKZj5Ccm5Jek1HYv3KXluFRv0HSo8FSo0JTo3Hbn9CdlvPTu3Afq7Mav9EWk1Lfr7Afg1Mas3Gcr8Kdl0GVt5MRm7DTjzERu0BfguLRr5Iev4FTo8GTuzJShxMWv3HXi5LauyJanuKat2ObvyIfp3IZswLcq3ObswJXqzNcjxBcu8KSo3OVm2Beo1EZv0FXk1CTsvJdo5LXu7HRq0PVn2FVl3JUp0AcqyEWizNcu5KTr5CdvuFfqvIZm0IdkyASh6Hdp6OYouBVt0Ibn9DVj7AWryLet6Acr2Ebk7FdpyAXtyOcmvJRp5FQtwDZmwGQmzAcg1NTnzJXg6PXq8ASg5MWjuOSvxFao0IUm9CVu1AeszESt9DYpzDZpvOVg0DcgzLUj0Lcj1LUr6Ibl0IctxGfg9PWn6Pbr6KUhwOej8IenxNclzEZg5BYu1LZr5Nel2HVozMWj9GZmwLUj2MXq6GSm6AUqyMVu6ORnxLcn5FYg5FUt1DVk7ITk1Ick5Kcr6OQo1OYpvKWj2MUkuNdp6Cbk0DZh7FStuIYu9PXgvITt0Eal7MZl7ISmwESm6OZh1NQo6HXj0Ias4Aem0EWvvOYgzJTjwNQu8HVvuFat0MVszLevwMcv7JSu1Cak2EZu6Gdq9OQgzKVjyFalvGWj6Ifr6HRs4GWvxHSluNTmwPVs4GXi8JSt3ObjvKcpxJfv3Pch1LYpzPSpuIVl9DdvyFam2BbmzAXivPTm8Lat0Ccv1OavyEVl6Jdk5BQiyOZv1MVp1LRjvDQlwHbnyFSv1AWn3BShwHcvxDdhyFZryGVi3DbmuOSk0JYk2CehwPdp3JQm7PWr9JTnvOVq5PclyLQjvJfr3IRpvIYn8CTt3OYm1FVjxKWv8Obo5IQjxLWp9Kbk7MRjyKTl0FdiuDSgzDdk1AeovHYkyLYnwITiyCUv5KTi4GQq7Jbn2IbrvHWqzBaixKSs4KaiuHSizNUivPSu9Cck2FQsvKftuFWq8HdpwMQqxFbh3KXouGcoyPVs9AZgwNag1LQh2CUh9DRu1Cfm2EYrwEUjuJTnxHQh4Cau1PWs9NQs0KRg7IVsyKRs0FUjyKfr6GSn3EVv5KRpxEZoxGRu5LXg3GUh1HQh6BWi1MUk9HUl0BRs4LYu6OTmuJRm1LRgzLbpzDYiuFfm3Ich4LZjuMZr7DVh8ESt4HahwNUpvEViwGWmzFVu1HUjzGZnxPfq5PSrxJRg2KUj0CXgvPUs8CVtyHWkxOVs6NUk9LWi0AZrxHTmzPQv1CRrxCTgvKWrvLdiuLXszGQq8JeovJXpvIYsuMdrvOeu3GXuuKag1GXpxDWpuKTh1Dbs2FRi5JYkzAXr9Nfl2MYh6FWl1BVpxBZg6DZq9JUjvJZlxBTiwGRqvPdmwFXr2AQg6EWiyIeq0KepzOSo0OQm8GTv7BWi0IVm7DYq6GVn8KUlwPWq3KRh0BQt3Lbq1CYo6DZq4FXm0Nep1FWp1Ibn1IdsyBQpwJdtxOZi9PZoxPbv1BRkxEfj8CXi0CZs2Ddu0KRr7Kdp7KZnyFcj9Ibq6Kaq6GbixLZn7Eat7Hbq9Dcs7MZt9HckuGZn3ASk2FSpxBWg8AXl7KUkvITkuPZu0IWk0FUo7KRu9OdhvCSi8PUq4Edi9Edq3DYo3KYv4OajvMel1JTswBTqzBfu4Odl8ASo2EQj2GekvMQs5LYn4OUm1IUnyGfq2Gdl1FWq6CenyJTnzJbr8Par2LTj8LaivBbguLZl3KXr7MasvMZm7IZmwJWm6MZs0NXo6Pbk9KZl6CaswKTs2PWn8Bet9OTqwPbl3LZk5Kcl2LZn5OVg1DXluBdizIQl8Lbv9Pcl7LQs1Pbk7HUozMZh1JQv8NTtyKTh2KQlzHbowEQj2HRp3NVv4KVo6AZr8AVs9EchwEWn4LRh5ASv0IVi8FTrxHRn7Lai6EdgvGcqvMas8KWrzMfmuDZo6AejvKRgyMZr9GYn5ERm4HfqyBRn3BcsyEepzDQg1LYqyGYvxLQixJUtyLVm2FWjuORi7NZn7LVo5LWrxIbk4Gdn1JSh6ASo6JZh4OUo4LZruLZu8KZrvBZh0MXuyMTv8Eat2JVo8JWnvHWn8AXtxFfj5IShzDYswHbqzDVv8ASp0JSrzKXl8DVjvMWg6KWn8BcgvAStzDUh8CfovKZh7PZlyMQkxAUs2JVo2DbiuGXv1DYp4NXpyLSu6HcqzEarzCRt2LZn6NUuvLbl8CWn6LTuxFSq1OXh3NWgwDYjxEXuxIXlvFRqyAfl5OVr7Lfu6MYm9AUs6CTt6EWuwBes9BSvwJSn7PXq9JZsuKZu9IUqwGRo9Leq6CWt2AWs3Pdg5OQouIXl8LYkxNav9DSqvAXr4PWl8JRv3PUp0BWrzDXm4GZlwAQhwCUh7FVo5GTmzFTg7OeuzMUh9BYlxGYn7Gar3BUg9Geg6FRj6KXg7ITh5OXt7Caj3Afq1CXo2Ifj9LQs8AWp2OZs5Dfs3EUk4DYk7ERhvJXnwJRovKTnuCYv7Nam4NYj7Iat5DRjuESq0Ddn0PYh3HZl2AQt9JWmyFXvzPWi4DRh5HfuuITm7HVu2Leh8PSk8OZo7Ddl2DQn2PUozNfs4Kdj2PSm4KaqwKck0PSs2BWpvGSguOUv2PWr2Oet5Laq8DWm7LXh8Bft5KQs5Man9CblvNdi5FQrxMZr2JWv3Hds9Ffn6Mbi5Oeq1DUv3Geh2MZg6JZm6AUmuEYj4Efo6NTk8IYgvCcqwGaj8DUuwHbuuLYq9GVjvBVn7FVr7IZkwDQt5Ndr2KUuxCfn1GTu8KcsyKWqxKbp2JRq3Ocp6OSj5Efl9CUm4Nao2Pah1ETguLZgwOcv2FTo5BdmwFes4BTmuDauyDTn1EXq2DVq1IRkzAUv6DTrwOQo8HQh8CbpxDRryORrvHfqvNbt9AfkwPQjzJVs0Ifl8Mbu1FUj0KYk2HUj0PZk7HUhyJTm7EfjvCRs4NYk0KYtzLcm8HUl2ATq8Mev3JWo8BYrxGcjuBTk5Lat5IdsyAUsvAco4FVu5PcnzCXu6PZl9MRhxCekuAeqvNVk0Ncv2Ebg2LSh2OVt1CSouHYl6Jfq6CXp4NYo2PYt3KRszARs3KRlvBXouDYn2FauzATk8Cel3Hak0MYj9EZh0HRr3KUl7KRl0GQvyPYp7GTlyEav2Nck0PZk8JZs3AZv5EbtxGXkuFbt4ESq7PThwDYiwAXt9EWkyGRm3HTs0GRt2OWs4JTl7LUl0PbjyESguHVl9PSv6Maj2JZtzNWi4CQj6OZr3FYu2OVtxERkwOcs0NWs4ESq8LftxPXl3Hbn6Jbp3HZk5FYlvIci5KcuzJRpvETv4NWtzNag2KYguGXhxGTsyDcvxCeu1GRo4Heh0GYuxIdhwNahwJYuwJUo0AUl9HSj4MZkyAdh7BQpvBZr8NSnxBWpuJVrzJep2Pdj8Oco8GYi5NSr8GZgvFQn8AXi6ObjxGZizMdi3OSjvKbh2FWv3DTt3IQo5NegyERv4HZi7Cbp6PYl4HdsuLfg2Icp4MRuxNQuvPUvyPQowPTs8LctyCQj5ARt8IToxJRk2Haj4OVj3PVs8BRs0NXpvPen9OXqyHQmvEQv6JXnxFWh1GRg6JSg2EarwLSjuAekvPduvMSqyGeh0OSuyJUr9IdguBcv9Bcn3CUmvPXj1AdnwBSl6Aak7NfpuFUt8AVpuIXj0AZr4CZt8Cfr6OatvGSt4FYr2KYh8LfnzKXjxPWuvIcuzFdr3BThwKdn2Ebm1NVnzHTnzJVh3HWnzAYl9CZg0Ffn9FVrzCXixAck0HfkxJUm4MVo9CXi0CRlxAQu2Mdm9ESgyHdpvKUv3CUv0GSquHRl6LXgvAdt0Gft6KfrwAWq5ETi1Odh0HbtzGZuvDSn2DZu5CTuzEWt7Fcq2KYq0MTs9DfixGRt2Adh0Dai8NXg5FUq4HSn8IUj0IevxHYl7CVsxOZg3IbhzLQtvDUo2CRouEbo1Edn0LQh8KQg4BXtvOam5PRt7PXlwCYvzAbq4BUgvNRp6GSouKep0BfmvCYk2HVh6HWv8PWk7ActuEXn5Adm7KQs0Adl0CUs1Kap1Ecg9Pbn4Nbj4OWm9Cds0GTj1JZszBcr4AQm3MVvyCcp9IWg3Aat8Efq6GQk4BVuuMVpyEYo8JYpwCVp6GatzMYm3BctxPfpzBRj1IYs4OahyEXmwHUquPRk7HVo1KWlvBSr0NasyHQr5Cfu4AXqvLcuyLanzGdsuHVr0DbjvNdn4MchvCUs0Ceq3JatyKQr5MUjwJSmxBXpwMbtuLap0EUl5Ldu3GfgwAWkxBUi9Kek8Gem6FeiuNRm3Ccm3JSrxAUk4CWg4LXquLRuwNUq6LUh7FQu5Nam8MVr5CbsuPXt9HWgzBTo9Icp4BeowGTj6GZh0Eft1EQivISl0DZnzBfg4KWjzCZuwLQk4NdrzJdv5AcqxGUj8ASm3LcqvKbl6PXhzAYhvDQo2HRuyORkvNToxFYq7Een0HZr6GVq4FYovLSn2EQj9IWj0JWt9AbvuNSouHWtzAXo3EQi2DbjwLZt0JZouFfsvDRsyETjvCSm2CWn5Kal2Ifu9FTr6LTn8IZi0DVr7FQpyNRuxMRh8DUq1KYt1MTi4IXi1FSvxGfo8MYrvAas7AXp2Nbp0Les4CWvuCblvGVh4MfhxJXn0Edj5HYqwGTt2MVtyMUhxBQlyAfl4Dai5LZn4AQlyGasyLUuwOWmxFbk2PdiwBag2HXp7Les1MSr8DUk2JUt9Ebi1BQu2LUt0CUi6KSs1PQsvEbrxAYhvHWsvCRj5PTtzBQtwKRpzCUjuGRh1LWvwKYr1MWlyHcnzLRp6AUn0GQtwJXs1GXs9CUqyDfpwNYi4BQq8CUr3Hdp5Jbj8EVl4Pdr1ISi2EVs5LRi0IVgzJdg3BVuuPcg6BZt6FZk7HRpvDeuxIen1CSp6DUivBTr2GXkzOQh2MWu7NUt6ARp5GWgzCYm3GXnuBeu2ATj2BVm1DcrwBUk1Pav6HSh4DVp9FVk2OSrwPTu1MSsvIVrvJQo6Lcs4HfvyCVjzIRgyDev6DRvuBRtxLaq0AbpyLQnxAbr9GRg5Ffv3GVgvOVpzDWqyMVt8OVl9MamzNaovCRu6OcqyDQmwGcj0Acg2LShwPavyPbi3HXp5GVs9CWr1PcqxJQi0Mdt4CTqzPeiyBdl4Jck1AcoxCQswKUqyCZn4EYpuDSu8Adh6PWizEdo7Idt7IWr3EVtzFUn0MahvKYrwJbovMXoxDfizNaovMfpvGbgyOZt6AQk1NVixBRp8Mbq8AQn8BUouEWiuLTqwCfpyFcg8Hcp0MajxLRh5NXtzMTh9BWm4BckuEan2Gbh9IWh8Hcl6Abp3ISt2IUu0Cet3IXkvCTt7MUmxMcv4GVu2LQt2MemyEfj2CbnuCcuvDUkwFakuAbi0GYtuFcj2Feu3Jen0EUl9JVuzEdp0KYhwMQr8PZrwJSuyPTj1IblxIeivNQk5PeuxKQmzOVk9PSo9AWtuNRjzMSi5Acq0Ifr5JYuwLauwNVq6KVtuBXl0KWg6ORlvOUlxERvvJei2AWn8IcryCUkuERn5Iat2JQr9Kdv7CQuwCXivGWgxMduxNetuCZh3HTt8NSjwDfpzPQl8HSi0CSq0Jeo1ETj3NWs0MQjyHdv8Lai7HYsyLYt5JfuyKQlxAUq3IRn1KdhvOfi4CSt2BZguATj3FTm0LcqzPXk7LdvxBRjvHenuKYr8NeuxBWn0JYi1OflzOWg7PVtuMSi0CZpzPbguOXvxPRg5DXn8Kam1Ier5CZu5FQp2HQvyBTuwJagxGRsyAUp2DfsvPajzGRlwEdovIar8Mai4IenxPYiuEXo6Mfr3EWmxMShwJdl9Ibt3DcivNTj1CZuwOdrvEUqyETj4Mev3OTmuJej8Ibl2DSk2NQv2CSgxEVi2DZtxOWhwNRi3Oft4Ncp9AUv4MTs1CYsuAQn9PQp5KUjuGYm9JRt4ORvvPUm4NcpvJcv1NTg0MUi2PQuzJQhyETpwKfi4Pbn3OVs7OcouJYn1Nau4Kdn1IYgwFWmvBQmwNRt2Jat1BSnvHQqwAevuGZtzCQt9Nal3PZj0NavuLbvwKXovIZv2Pcv6KWs2Ffr6LeuuAfmvOYo2GcjuHerwGbm0GSvzJZszNfqwJYpwKRl2JQgyNauwFbm1Har1LRt7MTvxGWguFcu0IXquFVr1IWqyHRvwOfpyKZixCTq5CctyOfu7IWo1LZo7Mcm0FbvzATuzLRv1MRv1IWmxKRovJVh5PZp1HRq6MZl2MWo3GUkvAWn2BRi3Mbl6FWv0DZu8Peg8ORsuARr1MZnwEdm4Dcn8GbuuCdj4Ccj8DYr3FUkwCbt6CRmyJeruKUp1GckvPYpzEUo6FZjxPTi8KZrwGUk4NThyIbiuGZrzNdj9BcsyAaszEUn8Mdg0CQp8BWl1Jaq0CYlxCTh1PQqyIQnzJQg1IYvxJZl3Mcg9PTvvIRsvNekvCQn9JYmyIflzKXp3KeoxGYt1EVq5Ben1HRi5EZm3MQnwIXg7FYp1CcluOaj0Abj0EYv4Lco9KWm1DXnxDZu8Dbp4Gco3LYj0JUo0KZjvHepvHRi9DVjuFar2Fbt7Ndl3DTv6IZt4Adl2HRg0OdnuOQv6FVt7Pfk5CVk4Bbt4FWozGds6Lck9MSt0NWhwPYkxMds2FVl3BQtvKSg4KUg9Jcp6BZh3FRszCYj0Fal0KSt2Ccu3PRtyGcmvAStvAZhvNYq6MQi6BbkuCTp2LWr5JVj1Jan1KZq7LbsyPem2GQq6BZm5KYo5OUi1NQo9Cck9KfnuObkvEbg0JVlyGVp9GYrwPcm8ORq9EVhxDZm9EZjuIRs8LRs5NYu6Pfn8ASv5KZp9MYr1JXm7EQk9GYo3NUswESv9ASp0Iap5GWuyLVo9DRn6NZixCTp6AWv8OSi8MSk7BTruHVpuIUn0Edv4MboyHau5Pfk3Eag6GYuxEci0PRu7LfswPTjwMYl3LSrzNUh9CQhvNVg0PTtyHXrzESj5PQi2NbpwPfh6EWi1Fas3FXgvDctzNfswIVkuAXi2GXnxARpyCYg0MeryDSu4GVo7JTo7Oap8AUp1GehzHcp6FWtvDWozEWm8OQm9CbovDVj6Dap1BcqwHbj7HTm6BWt5PRo1GQk1ARi9Oeu6Kdi9MfqwGcn7CUk8ORpzPSvuBTr1MfqvIbqxFcoyGbg0BRqvBXuyAcr7IfkvHci3ESqvNXhyNUl9Lfs5DQn6Hco8MZn3Ebp8BSi2OUkzCcoxFbs4KcrzMfvuETvuMYhvEWi9Kel7Pfr3DUu6IUp1DVq1CWo8Jft1EXkvEZr7AQm0KRp0Jcg2DVl1AYkyJbq7OfiwOekzHaj2MWi9OSsvMVv0PZi6Ifh6BVsvPQq1KWu8HVnyDcvvKUp6FTi1CQl2JUq8Dcu3MRn8LRo5CRt0DWn9Nav5Ffn1MViwFct1DWDSn4FVj4EdnwFSmuFRjxGTkxFQn6Quc42714435dbeb86fbb428357b328a88f20",
  aliasConfig: {
    appName: ["", "", ""],
    totalPageCount: [],
    largePageWidth: [],
    largePageHeight: [],
    normalPath: [],
    largePath: [],
    thumbPath: [],
    ToolBarsSettings: [],
    TitleBar: [],
    appLogoIcon: ["appLogoIcon"],
    appLogoLinkURL: ["appLogoLinkURL"],
    bookTitle: [],
    bookDescription: [],
    ButtonsBar: [],
    ShareButton: [],
    ShareButtonVisible: ["socialShareButtonVisible"],
    ThumbnailsButton: [],
    ThumbnailsButtonVisible: ["enableThumbnail"],
    ZoomButton: [],
    ZoomButtonVisible: ["enableZoomIn"],
    FlashDisplaySettings: [],
    MainBgConfig: [],
    bgBeginColor: ["bgBeginColor"],
    bgEndColor: ["bgEndColor"],
    bgMRotation: ["bgMRotation"],
    backGroundImgURL: ["mainbgImgUrl", "innerMainbgImgUrl"],
    pageBackgroundColor: ["pageBackgroundColor"],
    flipshortcutbutton: [],
    BookMargins: [],
    topMargin: [],
    bottomMargin: [],
    leftMargin: [],
    rightMargin: [],
    HTMLControlSettings: [],
    linkconfig: [],
    LinkDownColor: ["linkOverColor"],
    LinkAlpha: ["linkOverColorAlpha"],
    OpenWindow: ["linkOpenedWindow"],
    searchColor: [],
    searchAlpha: [],
    SearchButtonVisible: ["searchButtonVisible"],
    productName: [],
    homePage: [],
    enableAutoPlay: ["autoPlayAutoStart"],
    autoPlayDuration: ["autoPlayDuration"],
    autoPlayLoopCount: ["autoPlayLoopCount"],
    BookMarkButtonVisible: [],
    googleAnalyticsID: ["googleAnalyticsID"],
    OriginPageIndex: [],
    HardPageEnable: ["isHardCover"],
    UIBaseURL: [],
    RightToLeft: ["isRightToLeft"],
    LeftShadowWidth: ["leftPageShadowWidth"],
    LeftShadowAlpha: ["pageShadowAlpha"],
    RightShadowWidth: ["rightPageShadowWidth"],
    RightShadowAlpha: ["pageShadowAlpha"],
    ShortcutButtonHeight: [],
    ShortcutButtonWidth: [],
    AutoPlayButtonVisible: ["enableAutoPlay"],
    DownloadButtonVisible: ["enableDownload"],
    DownloadURL: ["downloadURL"],
    HomeButtonVisible: ["homeButtonVisible"],
    HomeURL: ["btnHomeURL"],
    BackgroundSoundURL: ["bacgroundSoundURL"],
    PrintButtonVisible: ["enablePrint"],
    toolbarColor: ["mainColor", "barColor"],
    loadingBackground: ["mainColor", "barColor"],
    BackgroundSoundButtonVisible: ["enableFlipSound"],
    FlipSound: ["enableFlipSound"],
    MiniStyle: ["userSmallMode"],
    retainBookCenter: ["moveFlipBookToCenter"],
    totalPagesCaption: ["totalPageNumberCaptionStr"],
    pageNumberCaption: ["pageIndexCaptionStrs"],
  },
  aliasLanguage: {
    frmPrintbtn: ["frmPrintCaption"],
    frmPrintall: ["frmPrintPrintAll"],
    frmPrintcurrent: ["frmPrintPrintCurrentPage"],
    frmPrintRange: ["frmPrintPrintRange"],
    frmPrintexample: ["frmPrintExampleCaption"],
    btnLanguage: ["btnSwicthLanguage"],
    btnTableOfContent: ["btnBookMark"],
    btnExitFullscreen: ["btnDisableFullScreen"],
    btnFullscreen: ["btnFullScreen"],
    btnHome: ["homebtnHelp"],
    btnMore: ["btnMoreOptionsLeft"],
    frmToc: ["btnBookMark"],
    frmSearch: ["btnSearch"],
    frmLinkLabel: ["lblLink"],
  },
  meta: {
    htmlTemplate: "Popular",
    theme: "Default",
    title: "Mẫu Thiết kế - Gia công Tem VN Check",
    description: "",
    url: "https://online.fliphtml5.com/nyrwe/zrbn/index.html",
    pageCount: 10,
    pageWidth: 1440,
    pageHeight: 810,
    template: "Popular",
  },
  "project-config": [],
  bmtConfig: [],
  videoList: [],
  staticAd: { haveAd: false },
  language: [
    {
      language: "English",
      btnFirstPage: "First",
      btnNextPage: "Next Page",
      btnLastPage: "Last",
      btnPrePage: "Previous Page",
      btnDownload: "Download",
      btnPrint: "Print",
      btnSearch: "Search",
      btnClearSearch: "Enter key to search",
      frmSearchPrompt: "Clear",
      btnBookMark: "Table of content",
      btnHelp: "Help",
      btnHome: "Home",
      btnFullscreen: "Fullscreen",
      btnSoundOn: "Sound On",
      btnSoundOff: "Sound Off",
      btnShareEmail: "Email",
      btnSocialShare: "Social Share",
      btnZoomIn: "Zoom In",
      btnZoomOut: "Zoom Out",
      btnDragToMove: "Move by mouse drag",
      btnAutoFlip: "Auto Flip",
      btnStopAutoFlip: "Stop Auto Flip",
      btnGoToHome: "Return Home",
      frmHelpCaption: "Help",
      frmHelpTip1: "Double click to zoom in or out",
      frmHelpTip2: "Drag the page corner to view",
      frmPrintCaption: "Print",
      frmPrintBtnCaption: "Print",
      frmPrintPreparePage: "Preparing Page:",
      frmPrintPrintFailed: "Print Failed:",
      pnlSearchInputInvalid: "The search text is too short.",
      loginCaption: "Login",
      loginInvalidPassword: "Not a valid password!",
      loginPasswordLabel: "Password:",
      loginBtnLogin: "Login",
      loginBtnCancel: "Cancel",
      btnThumb: "Thumbnails",
      lblPages: "Pages:",
      lblPagesFound: "Pages:",
      lblPageIndex: "Page",
      btnAbout: "About",
      frnAboutCaption: "About & Contact",
      btnSinglePage: "Single Page",
      btnDoublePage: "Double Page",
      tipChangeLanguage: "Please select a language below...",
      btnMoreOptionsRight: "More Options",
      btnFit: "Fit Window",
      smallModeCaption: "Click to view in fullscreen",
      btnAddAnnotation: "Add Annotations",
      btnAnnotation: "Annotations",
      FlipPageEditor_SaveAndExit: "Save and Exit",
      FlipPageEditor_Exit: "Exit",
      DrawToolWindow_Redo: "Redo",
      DrawToolWindow_Undo: "Undo",
      DrawToolWindow_Clear: "Clear",
      DrawToolWindow_Brush: "Brush",
      DrawToolWindow_Width: "Width",
      DrawToolWindow_Alpha: "Alpha",
      DrawToolWindow_Color: "Color",
      DrawToolWindow_Eraser: "Eraser",
      DrawToolWindow_Rectangular: "Rectangular",
      DrawToolWindow_Ellipse: "Ellipse",
      TStuff_BorderWidth: "Border Width",
      TStuff_BorderAlph: "Border Alpha",
      TStuff_BorderColor: "Border Color",
      DrawToolWindow_TextNote: "Text Note",
      AnnotMark: "Bookmarks",
      lastpagebtnHelp: "Last page",
      firstpagebtnHelp: "First page",
      aboubtnHelp: "About",
      screenbtnHelp: "Open this application in full-screen mode",
      helpbtnHelp: "Show help",
      searchbtnHelp: "Search from pages",
      pagesbtnHelp: "Take a look at the thumbnail of this brochure",
      bookmarkbtnHelp: "Open Bookmarks",
      AnnotmarkbtnHelp: "Open Table of content",
      printbtnHelp: "Print the brochure",
      soundbtnHelp: "Turn on or off the sound",
      sharebtnHelp: "Send Email to",
      socialSharebtnHelp: "Social Share",
      zoominbtnHelp: "Zoom in",
      downloadbtnHelp: "Downdlaod this brochure",
      pagemodlebtnHelp: "Switch Single and double page mode",
      languagebtnHelp: "Switch Lauguage",
      annotationbtnHelp: "Add Annotation",
      addbookmarkbtnHelp: "Add Bookmark",
      removebookmarkbtnHelp: "Remove Bookmark",
      updatebookmarkbtnHelp: "Update Bookmark",
      btnShoppingCart: "Shopping Cart",
      Help_ShoppingCartbtn: "Shopping Cart",
      Help_btnNextPage: "Next page",
      Help_btnPrePage: "Previous page",
      Help_btnAutoFlip: "Auto filp",
      Help_StopAutoFlip: "Stop atuo filp",
      btnaddbookmark: "Add",
      btndeletebookmark: "Delete",
      btnupdatebookmark: "Update",
      frmyourbookmarks: "Your bookmarks",
      frmitems: "items",
      DownloadFullPublication: "Full Publication",
      DownloadCurrentPage: "Current Page",
      DownloadAttachedFiles: "Attached Files",
      btnCopy: "Copy Button",
      infCopyToClipboard: "Your browser does not support clipboard.",
      restorePage: "Would you like to restore your previous session?",
      tmpl_Backgoundsoundon: "Background Sound On",
      tmpl_Backgoundsoundoff: "Background Sound Off",
      tmpl_Flipsoundon: "Flip Sound On",
      tmpl_Flipsoundoff: "Flip Sound Off",
      Help_PageIndex: "The current page number",
      tmpl_PrintPageRanges: "PAGE RANGES",
      tmpl_PrintPreview: "PREVIEW",
      btnSelection: "Select Text",
      loginNameLabel: "Name:",
      btnGotoPage: "Go",
      btnSettings: "Setting",
      soundSettingTitle: "Sound Setting",
      closeFlipSound: "Close Flip Sound",
      closeBackgroundSound: "Close Backgorund Sound",
      frmShareCaption: "Share",
      frmShareLinkLabel: "Link:",
      frmShareBtnCopy: "Copy",
      frmShareItemsGroupCaption: "Social Share",
      frmPanelTitle: "Share it",
      frmShareQRcode: "QRCode",
      TAnnoActionPropertyStuff_GotoPage: "Go to page",
      btnPageBack: "Backward",
      btnPageForward: "Forward",
      SelectTextCopy: "Copy Selected Text",
      selectCopyButton: "Copy",
      TStuffCart_TypeCart: "Shopping Cart",
      TStuffCart_DetailedQuantity: "Quantity",
      TStuffCart_DetailedPrice: "Price",
      ShappingCart_Close: "Close",
      ShappingCart_CheckOut: "Checkout",
      ShappingCart_Item: "Item",
      ShappingCart_Total: "Total",
      ShappingCart_AddCart: "Add to cart",
      ShappingCart_InStock: "In Stock",
      TStuffCart_DetailedCost: "Shipping cost",
      TStuffCart_DetailedTime: "Delivery time",
      TStuffCart_DetailedDay: "day(s)",
      ShappingCart_NotStock: "Not enough in stock",
      btnCrop: "Crop",
      btnDragButton: "Drag",
      btnFlipBook: "Flip Book",
      btnSlideMode: "Slide Mode",
      btnSinglePageMode: "Single Page Mode",
      btnVertical: "Vertical Mode",
      btnHotizontal: "Horizontal Mode",
      btnClose: "Close",
      btnBookStatus: "Book View",
      checkBoxInsert: "Insert Current Page",
      lblLast: "This is the last page.",
      lblFirst: "This is the first page.",
      lblFullscreen: "Click to view in fullscreen",
      lblName: "Name",
      lblPassword: "Password",
      lblLogin: "Login",
      lblCancel: "Cancel",
      lblNoName: "User name can not be empty.",
      lblNoPassword: "Password can not be empty.",
      lblNoCorrectLogin: "Please enter the correct user name and password.",
      btnVideo: "VideoGallery",
      btnSlideShow: "SlideShow",
      btnPositionToMove: "Move by mouse position",
      lblHelp1: "Drag the page corner to view",
      lblHelp2: "Double click to zoom in, out",
      lblCopy: "Copy",
      lblAddToPage: "add to page",
      lblPage: "Page",
      lblDescription: "Title",
      lblEdit: "Edit",
      lblDelete: "Delete",
      lblRemoveAll: "RemoveAll",
      tltCursor: "cursor",
      tltAddHighlight: "add highlight",
      tltAddTexts: "add texts",
      tltAddShapes: "add shapes",
      tltAddNotes: "add notes",
      tltAddImageFile: "add image file",
      tltAddSignature: "add signature",
      tltAddLine: "add line",
      tltAddArrow: "add arrow",
      tltAddRect: "add rect",
      tltAddEllipse: "add ellipse",
      lblDoubleClickToZoomIn: "Double click to zoom in.",
      frmShareLabel: "Share",
      frmShareInfo:
        "You can easily share this publication to social networks.Just cilck the appropriate button below.",
      frminsertLabel: "Insert to Site",
      frminsertInfo:
        "Use the code below to embed this publication to your website.",
      btnQRCode: "Click to scan QR code",
      btnRotateLeft: "Rotate Left",
      btnRotateRight: "Rotate Right",
      lblSelectMode: "Select view mode please.",
      frmDownloadPreview: "Preview",
      frmDownload: "Download",
      frmHowToUse: "How To Use",
      lblHelpPage1: "Move your finger to flip the book page.",
      lblHelpPage2: "Zoom in by using gesture or double click on the page.",
      lblHelpPage3:
        "Click on the logo to reach the official website of the company.",
      lblHelpPage4:
        "Add bookmarks, use search function and auto flip the book.",
      lblHelpPage5: "Switch horizontal and vertical view on mobile devices.",
      TTActionQuiz_PlayAgain: "Do you wanna play it again",
      TTActionQuiz_Ration: "Your ratio is",
      frmTelephone: "Telephone list",
      btnDialing: "Dialing",
      lblSelectMessage: "Please copy the the text content in the text box",
      btnSelectText: "Select Text",
      btnNote: "Annotation",
      btnPhoneNumber: "Telephone",
      btnWeCharShare: "WeChat Share",
      btnMagnifierIn: "Magnifying Glass",
      btnMagnifierOut: "Magnifier Reduction",
      frmShareSmallProgram: "smallProgram",
      btnMagnifier: "Magnifier",
      frmPrintPrintLimitFailed: "Sorry, you can't print the pages.",
      infNotSupportHtml5:
        "HTML5 is not supported by your current web browser, please read the book with latest verson web browser. Here we recommend you to read it with Chrome.",
      btnReport: "Report",
      btnDoubleSinglePage: "Page switch",
      btnDownloadPosterPrompt: "Click to download the poster",
      infLongPressToSavePoster:
        "Press and hold the mobile terminal to save the poster",
      infLongPressToIndentify: "Long press to identify QR code",
      infScanCodeToView: "Scan code to read",
      frmaboutcaption: "Contact",
      frmaboutDESCRIPTION: "Description",
      frmaboutAUTHOR: "Author",
      frmaboutADDRESS: "Address",
      frmaboutEMAIL: "Email",
      frmaboutWEBSITE: "Website",
      frmaboutMOBILE: "Mobile",
      infDeleteNote: "Do you want to delete the note?",
      proFullScreenWarn:
        "Current browser does not support full-screen,Please use Chrome for best results",
      btnBack: "Backs",
      frmVideoListTitle: "Video list",
      frmVideoTitle: "Video",
      lblConfirm: "Confirm",
      frmBookMark: "Book Mark",
      btnExitFullscreen: "Exit fullscreen",
      btnMore: "More",
      frmPrintall: "Print All Pages",
      frmPrintcurrent: "Print Current Page",
      frmPrintRange: "Print Range",
      frmPrintexample: "Example: 2,3,5-10",
      frmPrintbtn: "Print",
      frmaboutcontactinformation: "Contact Information",
      frmSearch: "Search",
      frmToc: "Table of Contents",
      btnTableOfContent: "Show Table of Contents",
      frmLinkLabel: "Link",
      frmQrcodeCaption:
        "Scan the bottom two-dimensional code to view with mobile phone.",
      btnLanguage: "Change Language",
      msgConfigMissing:
        "Configuration file is missing, unable to open the book.",
      lblSave: "Save",
      accessRestrictedTitle: "Access Restricted",
      enterYourName: "Enter your name",
      enterVisitCode: "Please enter your password",
      enterReadingCode: "enter your reading code",
      enterTheReason: "Enter your reason for application",
      enterPhoneNumber: "Enter your email address",
      enterVerificationCode: "Enter your verification code",
      getVerificationCode: "Send",
      sendValidCodeSuccess: "Verification code sent",
      getVerificationCodePrompt: "Get a verification code sent to your email",
      enterPasswordPrompt: "Password required to proceed reading",
      leaveMsgSimilarBooks: "Explore More Books",
      leaveMsgToAuthor: "Contact Author",
      leaveMsgName: "Your Name",
      leaveMsgContact: "Your Contact Information (visible only to the author)",
      leaveMsgEnter: "Please Enter the Message",
      leaveMsgCancel: "Cancel",
      leaveMsgCommitTitle: "Submit",
      leaveMsgPrompt: "We will forward your message to the book uploader.",
      leaveMsgErrorPrompt: "Exception occurred. Please try again later",
      readingCodeErrorPrompt: "Invalid reading code. Please try again",
      passwordErrorPrompt: "Invalid password. Please try again",
      invalidPhoneNumber: "Invalid number. Please try again",
      invalidEmail: "Invalid Email. Please try again",
      verificationCodeErrorPrompt:
        "Invalid verification code. Please try again",
      codeSendingFrequent: "Frequent operation, please try again later",
      commiteTitle: "Verify",
      shamStopTitle:
        "The author's account privileges have resulted in book access suspension.",
      shamStopSubTitle:
        "Contact <a target='_blank' href='{%host}/homepage/{%uLink}/' style='text-decoration: underline' >the author</a> for further information.",
      shamStopLeavePrompt: "Please complete the question.",
      shamStopLeaveMsgSuccessPrompt: "Send successfully",
      codeSending: "Sending",
      viewFullScreen: "Fullscreen",
      cardsSign: "click to view card",
      frmaboutViews: "Views",
      btnMessage: "Message",
      btnInstructions: "instructions",
      btnArticlePages: "Pages",
      btnArticleList: "Articles",
      btnCalendar: "Calendar",
      btnBook: "Book",
      btnEnlarge: "Enlarge",
      btnReduce: "Reduce",
      btnPrevArticle: "Prev Article",
      btnNextArticle: "Next Article",
      copySuccessfully: "Copy Successfully",
      cardsWechat: "Wechat",
      cardsTelephone: "phone",
      close: "close",
      jumpPageByEnterNumber:
        "Enter the page number to jump quickly to the specified page",
      jump: "Jump",
      relatedContent: "related information",
      brandTitleUndefined: "No brand name is set yet",
      more: "More",
      fold: "Put away",
      otherWorks: "other works",
      flipSound: "page turning sound",
      backgroundSound: "Background music",
      report: "report",
      copySuccessTip: "copy successfully",
      saveSuccessTip: "Saved successfully",
      scanCodeAddMy: "After saving, WeChat scan the code and add my friend",
      saveImg: "save Picture",
      searchTheBook: "Search this book content",
      historicalRecord: "history record",
      searchResultCount: "A total of {%count} results",
      noRelevantResults: "No relevant results",
      changeTheKeyWords: "Try another keyword ~",
      leastWordsTip: "Please enter at least 2 words",
      jumpPageInputTip:
        "Enter the page number to jump quickly to the specified page",
      jumpto: "Jump to",
      foldThumbnailTip: "Click here to put away the thumbnail ~",
      btnLoadingText: "In loading, it's fine soon",
      btnTitleText: "Read now",
      relatedInfoText: "Related Information",
      brandContactFrTitle: "Contact the author",
      shareFromPage: "Share starting from page N",
      TStuffShowInformatin_Width: "Background width",
      TStuffShowInformatin_Height: "Background height",
      TPageList_BlankPage: "Blank page",
      morePanelBookLink: "Link",
      morePanelPoster: "Poster",
      morePanelOtherShare: "Other",
      doublePageTitle: "Rotate the phone to enable double-page reading mode",
      doublePageDescription: "How to set landscape ?",
      doublePageGotIt: "Got it",
      doublePageAndroidSettingStep1: "1.The phone allows auto-rotation",
      doublePageAndroidSettingStep2:
        "2.The browser for reading e-books needs to be set to allow horizontal screen",
      doublePageAndroidSettingStep3:
        "3.Reading books with mobile phone turned sideways",
      doublePageIPhoneSettingStep1: "1.Phone portrait orientation lock off",
      doublePageIPhoneSettingStep2:
        "2.Reading books with mobile phone turned sideways",
      noFilesAvailablePrompt: "No Files Available!",
    },
  ],
  ols: [],
  slideshow: [],
  pageEditor: [],
  flipByAudio: null,
  downloadconfig: {
    pdf: null,
    isDownloadProject: false,
    isDownloadAttach: false,
    attachments: [],
    hideDownloadSinglePage: false,
  },
  assistantConfig: null,
  phoneNumber: [],
  bookPlugin: null,
  fliphtml5_pages: [
    {
      n: ["7a447702730439bf4c21111a78068193.webp"],
      t: "./files/thumb/69c45c90c191a5c166e9c41c2553e321.webp",
    },
    {
      n: ["c49e56afe0c546940ecf787e90b54453.webp"],
      t: "./files/thumb/53c8d33f5b3b72f9367f41065e623d54.webp",
    },
    {
      n: ["061c6aaadb59e8119a5963d2c6d62f15.webp"],
      t: "./files/thumb/1864b2b63a72fe4141858725ff97975f.webp",
    },
    {
      n: ["b5a70c286702e3f58b3169bdc9eeede0.webp"],
      t: "./files/thumb/fe48940edb4c8269f40b9020bf9c63e0.webp",
    },
    {
      n: ["cf0dfcaa182443f86820bbc1a531828e.webp"],
      t: "./files/thumb/9791419b2ef1764ae389b9ffe1aca725.webp",
    },
    {
      n: ["141efbb85270b915f6d93e73fb07993b.webp"],
      t: "./files/thumb/5941e88c854603dc64a943aad242a29c.webp",
    },
    {
      n: ["f2aef806ca330a82ac149f1f51ede6ee.webp"],
      t: "./files/thumb/0146c8911345dac6b2d3310e97c1c493.webp",
    },
    {
      n: ["94478da919e813723b90e188bd207ca6.webp"],
      t: "./files/thumb/8d6b844dcfdfae0fe1f283ef75effccd.webp",
    },
    {
      n: ["11fe0fca63c044636b16a17e56a7c21e.webp"],
      t: "./files/thumb/b6ac1a7f839a86e184de1639aeac8d52.webp",
    },
    {
      n: ["43ec5869acdbce2f2919845fd10ae3e5.webp"],
      t: "./files/thumb/d048431a7de38b4653db5dbea601683b.webp",
    },
  ],
  downloadConfig: null,
  fileExist: { pageEditor: 0, plugin: 0 },
  loadingConfig: {
    loadingBackground: "#323232",
    loadingCaptionColor: "#DDDDDD",
    loadingCaption: "",
    loadingCaptionFontSize: "20",
    loadingPicture: "",
    loadingPictureHeight: "150",
    showLoadingGif: "Yes",
    loadingVideo: "",
    loadingDisplayTime: "0",
  },
};
